# Generated by Django 6.0.6 on 2026-07-09 09:35

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("consignments", "0001_initial"),
        ("customers_tickets", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash - Hard physical currency counters"),
                            ("CARD", "Card - Retail POS EMV terminal hardware readers"),
                            (
                                "MOMO",
                                "MoMo - Domestic MoMo E-Wallet API gateway connection",
                            ),
                            (
                                "VNPAY",
                                "VNPAY - Interbank Napas QR-Code payment router network",
                            ),
                            (
                                "ZALOPAY",
                                "ZaloPay - Domestic ZaloPay business gateway endpoint",
                            ),
                            (
                                "BANK_TRANSFER",
                                "Bank Transfer - Automatic bank wire virtual accounts clearing",
                            ),
                            (
                                "CREDIT",
                                "Credit - In-app passenger CRM wallet currency balances",
                            ),
                        ],
                        help_text="System taxonomy identifier token tracking payment processors core routing rules",
                        max_length=30,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable user interface descriptive name shown to customers at checkout windows",
                        max_length=100,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="The official merchant service provider or third-party banking institution clearing the gateway operations",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Complex parameter matrix map capturing gateway credentials, client endpoints, and API secure hashes",
                    ),
                ),
                (
                    "sort_order",
                    models.SmallIntegerField(
                        default=0,
                        help_text="UI hierarchy ordering sequence value. Lower integers scale directly to the top of list maps",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Logical activation flag. Setting this parameter to False disables visibility on mobile/counter interfaces",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant corporate owner managing this isolated billing configurations node",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method Configuration",
                "verbose_name_plural": "Payment Method Configurations",
                "db_table": "payment_methods",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "payment_code",
                    models.CharField(
                        help_text="Unique system transaction lookup token key code (e.g., INV-2026-99A8X)",
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Payment billing code must contain only uppercase letters, numbers, hyphens, and underscores",
                                regex="^[A-Z0-9\\-_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The net currency scalar balance captured or requested under this specific billing invoice",
                        max_digits=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "PENDING",
                                "Pending - Invoice issued, awaiting execution gateway clearing",
                            ),
                            (
                                "SUCCESS",
                                "Success - Settlement confirmed, capital moved into system vaults",
                            ),
                            (
                                "FAILED",
                                "Failed - Transaction aborted, rejected by network clearing lines",
                            ),
                            (
                                "REFUNDED",
                                "Refunded - Financial commercial reversal processed back to customer",
                            ),
                            (
                                "EXPIRED",
                                "Expired - Session gate timeout limit breached before completion",
                            ),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="The current verification phase tracking this incoming payment execution",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_ref",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The external unique identification index string returned from bank gateway clearing networks",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        default=dict,
                        help_text="Raw JSON database tree mapping the absolute unedited telemetry response packet emitted by IPN callback webhooks",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware timestamp logging exactly when funds cleared gateway validation protocols",
                        null=True,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="The passenger reservation sheet being funded by this transaction line",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="customers_tickets.ticketbooking",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="The physical branch terminal hub office housing the cashier who logged the funds",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="branch_payments",
                        to="branches.branch",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        blank=True,
                        help_text="The offline front-office clerk or counter agent who hand-received the cash asset",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collected_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consignment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The logistics cargo consignment packet funded by this transaction line",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="consignments.consignment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant corporate owner who holds rights over this incoming cash flow ledger line",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        help_text="The configured channel path configuration through which this capital entry cleared",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="payments.paymentmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
                "db_table": "payments",
                "ordering": ["-created_at", "payment_code"],
            },
        ),
        migrations.CreateModel(
            name="CashierSession",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "opened_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.db.models.functions.datetime.Now,
                        help_text="Timezone-aware timestamp logging exactly when the cashier initialized the terminal drawer shift",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware timestamp logging when the cashier declared the shift finished and locked access keys",
                        null=True,
                    ),
                ),
                (
                    "opening_cash",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The opening cash floating balance inside the terminal drawer drawer at shift start",
                        max_digits=15,
                    ),
                ),
                (
                    "closing_cash",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The actual physical cash asset total counted by the employee at the end of the shift duration",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "total_sales",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The calculated mathematical sum of all revenue-generating tickets processed during this session",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "total_refunds",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The calculated mathematical sum of all cash payouts refunded out from this drawer during the shift",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "discrepancy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The calculated variance error metric (reported cash vs mathematically expected cash balance matrix)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "OPEN",
                                "Open - Active operational shift, capturing counter point-of-sale transactions",
                            ),
                            (
                                "CLOSED",
                                "Closed - Drawer locked, physical balance submitted, awaiting audit review",
                            ),
                            (
                                "RECONCILED",
                                "Reconciled - Audited by finance manager, variance cleared and ledger locked",
                            ),
                        ],
                        db_index=True,
                        default="OPEN",
                        help_text="The operational validation checkpoint phase tracking this cashier point-of-sale terminal sheet",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Explanations regarding cash drawer discrepancies, bank run delays, or unexpected power losses",
                        null=True,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="The physical branch terminal hub or office location where the transaction drawer is operated",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cashier_sessions",
                        to="branches.branch",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        help_text="The employee user account assigned to manage the physical cash drawer during this shift window",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cashier_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant corporate owner who holds rights over this physical point-of-sale shift node",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashier_sessions",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cashier POS Session",
                "verbose_name_plural": "Cashier POS Sessions",
                "db_table": "cashier_sessions",
                "ordering": ["-opened_at", "cashier"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["OPEN", "CLOSED", "RECONCILED"])
                        ),
                        name="chk_cashier_session_status_rules",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("opening_cash__gte", 0)),
                        name="chk_session_opening_cash_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "invoice_no",
                    models.CharField(
                        help_text="Official sequential invoice identification digit marker string (e.g., 00001234)",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invoice number must represent a numeric sequence matching statutory lengths",
                                regex="^[0-9]{1,8}$",
                            )
                        ],
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        help_text="Official statutory invoice symbol series prefix tracking registration year (e.g., 1C26TAA)",
                        max_length=10,
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(
                        blank=True,
                        help_text="Legal corporate entity name text or individual consumer name printed on the certificate header",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "buyer_tax_code",
                    models.CharField(
                        blank=True,
                        help_text="Government corporate business tax classification token needed for input tax deduction logs",
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Government buyer tax identification code format matrix is invalid",
                                regex="^[0-9\\-]{10,14}$",
                            )
                        ],
                    ),
                ),
                (
                    "buyer_address",
                    models.TextField(
                        blank=True,
                        help_text="Full corporate operational registration address text required by tax departments",
                        null=True,
                    ),
                ),
                (
                    "buyer_email",
                    models.EmailField(
                        blank=True,
                        help_text="Electronic mail destination endpoint where the signed XML/PDF invoice files are pushed automatically",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The net taxable operational revenue balance calculated prior to adding tax metrics",
                        max_digits=15,
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Statutory value added tax percentage rate scalar applied to sales (e.g., 8.00 or 10.00)",
                        max_digits=5,
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The absolute computed tax weight calculated dynamically from (subtotal * (vat_rate / 100))",
                        max_digits=15,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The eventual absolute gross invoice liability cash balance collected (subtotal + vat_amount)",
                        max_digits=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "DRAFT",
                                "Draft - Prepared workspace sheet, digital signature pending",
                            ),
                            (
                                "ISSUED",
                                "Issued - Digitally signed, authorized by tax authority portal, locked",
                            ),
                            (
                                "CANCELLED",
                                "Cancelled - Legally voided via official adjustment minute protocol",
                            ),
                            (
                                "REPLACED",
                                "Replaced - Voided and superseded by a corrective replacement invoice",
                            ),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="The internal operational progression phase state tracking this tax document item",
                        max_length=20,
                    ),
                ),
                (
                    "e_invoice_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique cryptographic reference lookup key hash returned by third-party e-invoice provider networks (e.g., Viettel SInvoice, VNPT, Misa MeInvoice)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "e_invoice_url",
                    models.CharField(
                        blank=True,
                        help_text="Cloud storage direct URL link matching online verification portal locations where the client downloads the official PDF copy",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware timestamp logging exactly when digital certificates signed this document block out to government systems",
                        null=True,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="The retail passenger reservation sheet bound to this financial tax document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="customers_tickets.ticketbooking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "group_contract",
                    models.ForeignKey(
                        blank=True,
                        help_text="The corporate B2B chart contract order document bound to this financial tax document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="customers_tickets.groupcontract",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The licensed internal staff accountant executing the digital gateway HSM signature",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant corporate corporate owner holding local fiscal rights over this tax document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal VAT Invoice",
                "verbose_name_plural": "Legal VAT Invoices",
                "db_table": "invoices",
                "ordering": ["-created_at", "invoice_no"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["DRAFT", "ISSUED", "CANCELLED", "REPLACED"])
                        ),
                        name="chk_invoice_status_rules",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("subtotal__gte", 0),
                            ("vat_amount__gte", 0),
                            ("total_amount__gte", 0),
                        ),
                        name="chk_invoice_amounts_positive",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="paymentmethod",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="unique_tenant_payment_method_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentmethod",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "code__in",
                        [
                            "CASH",
                            "CARD",
                            "MOMO",
                            "VNPAY",
                            "ZALOPAY",
                            "BANK_TRANSFER",
                            "CREDIT",
                        ],
                    )
                ),
                name="chk_payment_method_code_rules",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["PENDING", "SUCCESS", "FAILED", "REFUNDED", "EXPIRED"],
                    )
                ),
                name="chk_payment_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="chk_payment_amount_positive",
            ),
        ),
    ]
