# Generated by Django 6.0.6 on 2026-06-18 03:12

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the webhook", max_length=100
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="URL to send webhook events to",
                        max_length=500,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "secret_hash",
                    models.CharField(
                        blank=True,
                        help_text="HMAC-SHA256 secret for signing requests",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "events",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        default=list,
                        help_text="List of events to subscribe to",
                    ),
                ),
                (
                    "timeout_sec",
                    models.SmallIntegerField(
                        default=10,
                        help_text="Request timeout in seconds",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "retry_count",
                    models.SmallIntegerField(
                        default=3,
                        help_text="Number of retry attempts on failure",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom headers to include in requests",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Webhook is active and will receive events",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this webhook",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhooks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this webhook",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Endpoint",
                "verbose_name_plural": "Webhook Endpoints",
                "db_table": "webhook_endpoints",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text='Event type (e.g., "booking.created")',
                        max_length=100,
                    ),
                ),
                ("payload", models.JSONField(help_text="Event payload as JSON")),
                (
                    "response_code",
                    models.SmallIntegerField(
                        blank=True, help_text="HTTP response status code", null=True
                    ),
                ),
                (
                    "response_body",
                    models.TextField(
                        blank=True,
                        help_text="HTTP response body (truncated)",
                        null=True,
                    ),
                ),
                (
                    "attempt",
                    models.SmallIntegerField(default=1, help_text="Attempt number"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending - Waiting to send"),
                            ("SUCCESS", "Success - Delivered successfully"),
                            ("FAILED", "Failed - Delivery failed"),
                            ("RETRY", "Retry - Retry scheduled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Delivery status",
                        max_length=20,
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, help_text="When delivery was successful", null=True
                    ),
                ),
                (
                    "failed_at",
                    models.DateTimeField(
                        blank=True, help_text="When delivery failed", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        help_text="Webhook endpoint",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="webhooks.webhookendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Delivery",
                "verbose_name_plural": "Webhook Deliveries",
                "db_table": "webhook_deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="webhookendpoint",
            index=models.Index(
                fields=["tenant", "is_active"], name="idx_webhook_tenant_active"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookendpoint",
            index=models.Index(fields=["events"], name="idx_webhook_events"),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["endpoint", "status"], name="idx_wk_deliver_endpoint"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["-created_at"], name="idx_webhook_deliveries_created"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["event_type"], name="idx_webhook_deliveries_event"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["status", "attempt"], name="idx_webhook_deliveries_retry"
            ),
        ),
    ]
