# Generated by Django 6.0.6 on 2026-07-07 02:33

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text='Human-readable name for the token (e.g., "Mobile App")',
                        max_length=100,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA256 hash of the token (never store raw token)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "token_prefix",
                    models.CharField(
                        db_index=True,
                        help_text="First 8 characters of token for identification",
                        max_length=8,
                    ),
                ),
                (
                    "scopes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        default=list,
                        help_text="List of scopes this token has access to",
                    ),
                ),
                (
                    "branch_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Optional branch ID for branch-specific tokens",
                        null=True,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, help_text="When this token was last used", null=True
                    ),
                ),
                (
                    "last_used_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of last usage", null=True
                    ),
                ),
                (
                    "request_count",
                    models.BigIntegerField(
                        default=0,
                        help_text="Total number of requests made with this token",
                    ),
                ),
                (
                    "rate_limit",
                    models.IntegerField(
                        default=1000,
                        help_text="Maximum requests per hour",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Token expires at this date (null = no expiration)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Token is active and can be used",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this token",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this token",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_tokens_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this API token",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Token",
                "verbose_name_plural": "API Tokens",
                "db_table": "api_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APITokenAuditLog",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create - Token created"),
                            ("REVOKE", "Revoke - Token revoked"),
                            ("ACCESS", "Access - Token used for API request"),
                            ("RATE_LIMIT", "Rate Limit - Rate limit exceeded"),
                            ("SCOPE_DENIED", "Scope Denied - Insufficient scope"),
                        ],
                        db_index=True,
                        help_text="Type of action",
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        help_text="HTTP method (GET, POST, etc.)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        blank=True,
                        help_text="API endpoint accessed",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True, help_text="HTTP response status code", null=True
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of request", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent of request", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this audit log",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_token_audit_logs",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        help_text="API token used",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_token_audit_logs",
                        to="api_tokens.apitoken",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Token Audit Log",
                "verbose_name_plural": "API Token Audit Logs",
                "db_table": "api_token_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="apitoken",
            index=models.Index(fields=["is_active"], name="idx_api_tokens_active"),
        ),
        migrations.AddIndex(
            model_name="apitoken",
            index=models.Index(fields=["token_prefix"], name="idx_api_tokens_prefix"),
        ),
        migrations.AddIndex(
            model_name="apitoken",
            index=models.Index(
                fields=["tenant", "is_active"], name="idx_api_tokens_tenant_active"
            ),
        ),
        migrations.AddIndex(
            model_name="apitoken",
            index=models.Index(fields=["expires_at"], name="idx_api_tokens_expires"),
        ),
        migrations.AddIndex(
            model_name="apitokenauditlog",
            index=models.Index(
                fields=["token", "created_at"], name="idx_api_audit_token_created"
            ),
        ),
        migrations.AddIndex(
            model_name="apitokenauditlog",
            index=models.Index(fields=["action"], name="idx_api_audit_action"),
        ),
    ]
