# Generated by Django 6.0.5 on 2026-06-09 08:34

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("branches", "0001_initial"),
        ("routes", "0001_initial"),
        ("tenants", "0001_initial"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consignment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "waybill_code",
                    models.CharField(
                        help_text="Unique human-readable tracking index string token (e.g., WAY-1002-X89)",
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Waybill tracking code must contain only uppercase letters, numbers, hyphens, and underscores",
                                regex="^[A-Z0-9\\-_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        help_text="Standardized 1D barcode sequence mapped onto physical paper shipping labels for scanner guns",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(
                        blank=True,
                        help_text="High-density 2D matrix QR token enabling fast mobile camera manifest scans on bến bãi floors",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        help_text="Full individual name or corporate company text shipping this package line",
                        max_length=255,
                    ),
                ),
                (
                    "sender_phone",
                    models.CharField(
                        db_index=True,
                        help_text="Primary contact mobile number sequence tracking originating client accounts",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Sender phone contact compilation sequence is invalid",
                                regex="^\\+?[0-9\\s\\-]{7,20}$",
                            )
                        ],
                    ),
                ),
                (
                    "receiver_name",
                    models.CharField(
                        help_text="Full legal individual identity name authorized to claim or pull the package at target counters",
                        max_length=255,
                    ),
                ),
                (
                    "receiver_phone",
                    models.CharField(
                        db_index=True,
                        help_text="Primary mobile sequence utilized to dispatch arrival notice automated SMS text lines",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Receiver phone contact compilation sequence is invalid",
                                regex="^\\+?[0-9\\s\\-]{7,20}$",
                            )
                        ],
                    ),
                ),
                (
                    "cargo_type",
                    models.CharField(
                        blank=True,
                        help_text="Classification category grouping layout matching the pricing engine rules matrix (e.g., FRAGILE, NORMAL)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed content declarations required for freight safety checking (e.g., Red Asus Laptop inside leather sleeve)",
                        null=True,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The physical scale mass value metric calculated in kilograms (KG)",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "volume_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Volumetric spatial calculation tracking dimensional capacity occupied inside chassis decks in cubic meters (M3)",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                    ),
                ),
                (
                    "declared_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The customer estimated cash valuation of parcel properties used to establish safety liability caps",
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "freight_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The core tariff transport operational fee invoice price assessed to move the cargo unit",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "insurance_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Surcharge applied to high-value items protecting the tenant against financial indemnity claims",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "cod_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Cash-on-delivery collection threshold target to collect from receiver before handover approval",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "cod_collected",
                    models.BooleanField(
                        default=False,
                        help_text="Boolean verification flag logging if counter clerk physically captured the cash during delivery handover",
                    ),
                ),
                (
                    "cod_transferred",
                    models.BooleanField(
                        default=False,
                        help_text="Accounting audit flag confirming system successfully transferred collected COD funds back into sender accounts",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "RECEIVED",
                                "Received - Parcel accepted at origin counter hub branch warehouse",
                            ),
                            (
                                "LOADED",
                                "Loaded - Cargo packed and secured inside vehicle trunk compartment",
                            ),
                            (
                                "IN_TRANSIT",
                                "In Transit - Vehicle is actively navigating the trip route",
                            ),
                            (
                                "ARRIVED",
                                "Arrived - Unloaded at target destination station terminal floor",
                            ),
                            (
                                "DELIVERED",
                                "Delivered - Parcel successfully signed off and handed over to receiver",
                            ),
                            (
                                "RETURNED",
                                "Returned - Rejected or undeliverable, routed back to original sender",
                            ),
                            (
                                "LOST",
                                "Lost - Proximity search failed, marked missing in operations",
                            ),
                            (
                                "DAMAGED",
                                "Damaged - Structural package integrity broken or compromised during transit",
                            ),
                        ],
                        db_index=True,
                        default="RECEIVED",
                        help_text="The current logistics lifecycle milestone phase tracking this parcel through processing grids",
                        max_length=30,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Operational alerts such as secondary recipient authorization notes or localized damage annotations",
                        null=True,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware timestamp logging exactly when intake clerks committed initial entry protocols",
                        null=True,
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware timestamp logging exactly when final client signed off the delivery certificate",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="System record logging anchor tracking exactly when this record line row entered the main database",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp tracking exactly when attributes inside this logistics row node were modified",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="The physical corporate retail office terminal location currently managing the item lifecycle",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consignments",
                        to="branches.branch",
                    ),
                ),
                (
                    "delivered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The delivery window desk counter agent who confirmed cash capture and handed parcel to customer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivered_consignments",
                        to="accounts.useraccount",
                    ),
                ),
                (
                    "destination_station",
                    models.ForeignKey(
                        blank=True,
                        help_text="The target destination station hub node where the parcel is destined to be picked up",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination_consignments",
                        to="routes.station",
                    ),
                ),
                (
                    "origin_station",
                    models.ForeignKey(
                        blank=True,
                        help_text="The physical origin station hub node where the package was dropped off",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origin_consignments",
                        to="routes.station",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The intake desk clerk user profile account who scanned the parcel into origin storage inventory",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_consignments",
                        to="accounts.useraccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant corporate owner holding legal data sovereignty over this cargo parcel log",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consignments",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        help_text="The active vehicle journey transit route assigned to convey this physical bưu kiện",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consignments",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo Consignment",
                "verbose_name_plural": "Cargo Consignments",
                "db_table": "consignments",
                "ordering": ["-created_at", "waybill_code"],
            },
        ),
        migrations.CreateModel(
            name="CodReconciliation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The precise mathematical cash currency total amount to be paid back out to the parcel sender client",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "PENDING",
                                "Pending - Cash collected at counter, awaiting accountant clearance approval",
                            ),
                            (
                                "TRANSFERRED",
                                "Transferred - Outbound bank dispatch executed, funds sent to parcel sender",
                            ),
                            (
                                "CONFIRMED",
                                "Confirmed - Client confirmed receipt or bank statement webhook matched successfully",
                            ),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="The accounting audit phase tracking this cash settlement through clearance banking pipelines",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Bank transaction sequence hashes, account details, or manual tracking annotations for discrepancies",
                        null=True,
                    ),
                ),
                (
                    "transferred_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware timestamp logging exactly when the bank transfer API or cash desk pushed out the money",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now,
                        help_text="System record logging anchor tracking exactly when this reconciliation row was opened inside the core DB",
                    ),
                ),
                (
                    "transferred_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The financial staff user or accountant account who cleared the payout and signed the bank voucher",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_cod_settlements",
                        to="accounts.useraccount",
                    ),
                ),
                (
                    "consignment",
                    models.ForeignKey(
                        help_text="The specific source parcel consignment document whose cash flow liability is managed here",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cod_reconciliations",
                        to="consignments.consignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "COD Cash Reconciliation",
                "verbose_name_plural": "COD Cash Reconciliations",
                "db_table": "cod_reconciliations",
                "ordering": ["-created_at", "status"],
            },
        ),
        migrations.CreateModel(
            name="ConsignmentEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            (
                                "STATUS_CHANGE",
                                "Status Change - State mutation tracking timeline adjustments",
                            ),
                            (
                                "NOTE",
                                "Note - Hand-written operational text memo or customer alert annotations",
                            ),
                            (
                                "SCAN",
                                "Scan - Hardware scanner laser gun ping logging warehouse floor checkpoint presence",
                            ),
                            (
                                "PHOTO",
                                "Photo - Optical imagery attachment asset tracking packaging structural integrity",
                            ),
                        ],
                        help_text="The primary structural action classification assigned to this timeline snapshot row",
                        max_length=30,
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        help_text="The previous state string cloned from parent logs prior to executing mutations (e.g., RECEIVED)",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        help_text="The target current state string mapped down onto the parent log (e.g., LOADED)",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descriptive telemetry summaries or specific event context text data blocks (e.g., Packed inside Truck 29B-123.45)",
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical office text string or text description logging where the action executed",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now,
                        help_text="Timezone-aware timestamp logging exactly when this micro-action entered database storage frameworks",
                    ),
                ),
                (
                    "consignment",
                    models.ForeignKey(
                        help_text="The parent parcel transport ledger line being audited by this telemetry timestamp snapshot",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="consignments.consignment",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The employee profile account or system background daemon executing this tracking snapshot log",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logged_consignment_events",
                        to="accounts.useraccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consignment Journey Event",
                "verbose_name_plural": "Consignment Journey Events",
                "db_table": "consignment_events",
                "ordering": ["consignment", "-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsignmentManifest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "manifest_code",
                    models.CharField(
                        help_text="Unique human-readable system manifest identity string token (e.g., MNF-HANOI-2026-X9A)",
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Manifest tracking code must contain only uppercase letters, numbers, hyphens, and underscores",
                                regex="^[A-Z0-9\\-_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "OPEN",
                                "Open - Active batching workspace, accepting package additions and scans",
                            ),
                            (
                                "CLOSED",
                                "Closed - Sealed batch sheet, cargo locked, awaiting yard driver gate release",
                            ),
                            (
                                "DISPATCHED",
                                "Dispatched - Vehicle cleared terminal gates, manifest is actively in transit",
                            ),
                        ],
                        db_index=True,
                        default="OPEN",
                        help_text="The operational validation phase tracking this aggregated shipment listing through transport loops",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now,
                        help_text="Timezone-aware timestamp logging exactly when this manifest row layout was opened inside the database",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific logistics officer or warehouse clerk who compiled and authorized the cargo loading sheet",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_manifests",
                        to="accounts.useraccount",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        help_text="The specific active vehicle fleet journey assigned to physically transport this consolidated batch",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consignment_manifests",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consignment Manifest",
                "verbose_name_plural": "Consignment Manifests",
                "db_table": "consignment_manifests",
                "ordering": ["-created_at", "manifest_code"],
            },
        ),
        migrations.CreateModel(
            name="ManifestItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "loaded_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now,
                        help_text="Timezone-aware timestamp logging exactly when the warehouse laser gun scanned this item into the trip batch",
                    ),
                ),
                (
                    "consignment",
                    models.ForeignKey(
                        help_text="The explicit separate cargo package object being packed into the vehicle deck space",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manifest_links",
                        to="consignments.consignment",
                    ),
                ),
                (
                    "manifest",
                    models.ForeignKey(
                        help_text="The parent batch manifest document compiling this cargo structural entry lines",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manifest_items",
                        to="consignments.consignmentmanifest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manifest Cargo Item",
                "verbose_name_plural": "Manifest Cargo Items",
                "db_table": "manifest_items",
                "ordering": ["manifest", "-loaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CargoPriceTable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cargo_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "NORMAL",
                                "Normal - Standard dry non-perishable general parcel boxes",
                            ),
                            (
                                "FRAGILE",
                                "Fragile - Delicate breakable items requiring specialized shock protection",
                            ),
                            (
                                "LIQUID",
                                "Liquid - Fluids or chemical barrels demanding secondary containment sets",
                            ),
                            (
                                "FROZEN",
                                "Frozen - Cold-chain climate-controlled thermal freight lines",
                            ),
                            (
                                "OVERSIZED",
                                "Oversized - Volumetric bulky assets exceeding standard luggage compartments",
                            ),
                            (
                                "HAZARDOUS",
                                "Hazardous - Regulated combustible compounds or lithium cells",
                            ),
                        ],
                        db_index=True,
                        help_text="The specialized transport properties group classification assigned to this matrix rule line",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "min_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The inclusive lower mass boundary benchmark requirement calculated in kilograms (KG)",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The inclusive upper mass boundary benchmark requirement calculated in kilograms (KG)",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "min_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="The inclusive lower spatial dimension volume check calculation threshold in cubic meters (M3)",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "max_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="The inclusive upper spatial dimension volume check calculation threshold in cubic meters (M3)",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The gross core billing tariff coefficient rate value assigned to this rule setup configuration",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "price_unit",
                    models.CharField(
                        choices=[
                            (
                                "PER_KG",
                                "Per Kilogram - Cost calculated multiplying scale weight increments",
                            ),
                            (
                                "PER_TRIP",
                                "Per Trip - Structural logistics charge calculated per route execution block",
                            ),
                            (
                                "FLAT",
                                "Flat - Static invariant standard processing fee applied to parcel item unit",
                            ),
                            (
                                "PER_M3",
                                "Per Cubic Meter - Spatial dimensional volume layout multiplication rate",
                            ),
                        ],
                        db_index=True,
                        default="PER_KG",
                        help_text="The evaluation formula methodology applied to calculate eventual final customer parcel invoice values",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Active validation switch flag. Turning this off flags the matching arithmetic engine to skip evaluating this row entry",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this logistics tariff row rule was opened inside the core database layout",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when structural parameters inside this dynamic tariff node were last modified",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific geography transport route assigned to this tariff rate. If NULL, acts as a global baseline rule.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cargo_tariffs",
                        to="routes.route",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant corporate owner managing this isolated logistics tariffs configuration leaf",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargo_price_tables",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo Pricing Rule",
                "verbose_name_plural": "Cargo Pricing Rules",
                "db_table": "cargo_price_tables",
                "ordering": [
                    "tenant_id",
                    "route_id",
                    "cargo_type",
                    "min_weight",
                    "price",
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "cargo_type__in",
                                [
                                    "NORMAL",
                                    "FRAGILE",
                                    "LIQUID",
                                    "FROZEN",
                                    "OVERSIZED",
                                    "HAZARDOUS",
                                ],
                            ),
                            ("cargo_type__isnull", True),
                            _connector="OR",
                        ),
                        name="chk_cargo_pricing_type_enum",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("price_unit__in", ["PER_KG", "PER_TRIP", "FLAT", "PER_M3"])
                        ),
                        name="chk_cargo_pricing_unit_enum",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("price__gte", 0)),
                        name="chk_cargo_pricing_value_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("max_weight__gte", models.F("min_weight")),
                            ("max_weight__isnull", True),
                            ("min_weight__isnull", True),
                            _connector="OR",
                        ),
                        name="chk_cargo_pricing_weight_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("max_volume__gte", models.F("min_volume")),
                            ("max_volume__isnull", True),
                            ("min_volume__isnull", True),
                            _connector="OR",
                        ),
                        name="chk_cargo_pricing_volume_range",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="consignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "RECEIVED",
                            "LOADED",
                            "IN_TRANSIT",
                            "ARRIVED",
                            "DELIVERED",
                            "RETURNED",
                            "LOST",
                            "DAMAGED",
                        ],
                    )
                ),
                name="chk_consignment_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="consignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("freight_charge__gte", 0),
                    ("insurance_fee__gte", 0),
                    ("cod_amount__gte", 0),
                ),
                name="chk_consignment_money_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="codreconciliation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["PENDING", "TRANSFERRED", "CONFIRMED"])
                ),
                name="chk_cod_reconciliation_status_rules",
            ),
        ),
        migrations.AddConstraint(
            model_name="codreconciliation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="chk_cod_reconciliation_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="consignmentevent",
            index=models.Index(
                fields=["consignment", "-recorded_at"], name="idx_consignment_events"
            ),
        ),
        migrations.AddConstraint(
            model_name="consignmentevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("event_type__in", ["STATUS_CHANGE", "NOTE", "SCAN", "PHOTO"])
                ),
                name="chk_consignment_event_type_enum",
            ),
        ),
        migrations.AddConstraint(
            model_name="consignmentmanifest",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["OPEN", "CLOSED", "DISPATCHED"])),
                name="chk_consignment_manifest_status_rules",
            ),
        ),
        migrations.AddConstraint(
            model_name="manifestitem",
            constraint=models.UniqueConstraint(
                fields=("manifest", "consignment"), name="uq_manifest_consignment_item"
            ),
        ),
    ]
