# Generated by Django 6.0.6 on 2026-07-09 09:35

import django.core.validators
import django.db.models.deletion
import tenants.models.tenant_feature_flag
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Mã định danh tenant (VD: DINHANH, VEXPRESS)",
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code chỉ chứa chữ hoa, số và dấu gạch dưới",
                                regex="^[A-Z0-9_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Tên công ty nhà xe", max_length=255),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="Domain tùy chỉnh nếu là SaaS",
                        max_length=255,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        help_text="URL logo công ty",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Màu chính của giao diện",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Màu phải ở định dạng hex (#RRGGBB)",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("TRIAL", "Trial"),
                            ("STANDARD", "Standard"),
                            ("PROFESSIONAL", "Professional"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        db_index=True,
                        default="STANDARD",
                        help_text="Gói dịch vụ",
                        max_length=30,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("VND", "Vietnam Dong (₫)"), ("USD", "US Dollar ($)")],
                        default="VND",
                        help_text="Đơn vị tiền tệ mặc định của nhà xe",
                        max_length=10,
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        help_text="Tỉ giá quy đổi so với đồng tiền gốc của hệ thống (VD: Hệ thống dùng USD, tỉ giá VND là 25000.0000)",
                        max_digits=12,
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        choices=[
                            ("vi", "Vietnamese/Tiếng Việt"),
                            ("en", "English/Tiếng Anh"),
                        ],
                        default="vi",
                        help_text="Ngôn ngữ hiển thị mặc định cho backend/frontend của tenant",
                        max_length=10,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[("Asia/Ho_Chi_Minh", "Asia/Ho_Chi_Minh (GMT+7)")],
                        default="Asia/Ho_Chi_Minh",
                        help_text="Múi giờ của nhà xe để đồng bộ thời gian chạy xe, lịch trình",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Tenant có hoạt động không",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cấu hình override cấp tenant",
                    ),
                ),
                (
                    "subscription_started_at",
                    models.DateTimeField(
                        blank=True, help_text="Ngày bắt đầu gói dịch vụ", null=True
                    ),
                ),
                (
                    "subscription_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Ngày hết hạn gói dịch vụ", null=True
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(default=10, help_text="Số lượng user tối đa"),
                ),
                (
                    "max_branches",
                    models.IntegerField(
                        default=1, help_text="Số lượng chi nhánh tối đa"
                    ),
                ),
                (
                    "max_vehicles",
                    models.IntegerField(default=50, help_text="Số lượng xe tối đa"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "tenants",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["code", "is_active"], name="tenants_code_007690_idx"
                    ),
                    models.Index(
                        fields=["plan", "is_active"], name="tenants_plan_09dc53_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted__isnull", True)),
                        fields=("code",),
                        name="unique_active_tenant_code",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("deleted__isnull", True)),
                        fields=("domain",),
                        name="unique_active_tenant_domain",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantInvitation",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("invited_by_id", models.IntegerField()),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Invitation",
                "verbose_name_plural": "Tenant Invitations",
                "db_table": "tenant_invitations",
            },
        ),
        migrations.CreateModel(
            name="TenantAuditLog",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("EXPORT", "Export"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("module", models.CharField(db_index=True, max_length=100)),
                (
                    "object_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("object_id", models.CharField(blank=True, max_length=50, null=True)),
                ("object_repr", models.TextField(blank=True, null=True)),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("changes", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_audit_logs",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Audit Log",
                "verbose_name_plural": "Tenant Audit Logs",
                "db_table": "tenant_audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="tenant_audi_tenant__2eeaa4_idx",
                    ),
                    models.Index(
                        fields=["module", "action"],
                        name="tenant_audi_module_1fcbc2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantFeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Mã feature (VD: ADVANCED_REPORTING)",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "rollout_percentage",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Phần trăm rollout (0-100)",
                        validators=[
                            tenants.models.tenant_feature_flag.validate_percentage
                        ],
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_feature_flags",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Feature Flag",
                "verbose_name_plural": "Tenant Feature Flags",
                "db_table": "tenant_feature_flags",
                "unique_together": {("tenant", "code")},
            },
        ),
    ]
