# Generated by Django 6.0.6 on 2026-07-07 12:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Mã định danh tenant (VD: DINHANH, VEXPRESS)",
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Code chỉ chứa chữ hoa, số và dấu gạch dưới",
                        regex="^[A-Z0-9_]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="domain",
            field=models.CharField(
                blank=True,
                help_text="Domain tùy chỉnh nếu là SaaS",
                max_length=255,
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="tenantauditlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenant_audit_logs",
                to="tenants.tenant",
            ),
        ),
    ]
