# Generated by Django 6.0.5 on 2026-06-09 08:34

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("hr", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="The unique descriptive name of the asset category group (e.g., Garage Repair Machinery, Office Electronics)",
                        max_length=100,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now,
                        help_text="Timezone-aware database anchor tracking exactly when this asset category configuration row was initialized",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant corporate node holding legal data sovereignty over this inventory catalog segment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_categories",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Category",
                "verbose_name_plural": "Asset Categories",
                "db_table": "asset_categories",
                "ordering": ["tenant_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique localized alphanumeric asset tag bar-code string identifier (e.g., FIX-EQUIP-0092)",
                        max_length=30,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full commercial description descriptive name label of the physical hardware asset unit",
                        max_length=255,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="The raw factory hardware engraving serial number string provided by the original manufacturer",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True,
                        help_text="The official calendar commercial procurement date matching invoice purchase receipts",
                        null=True,
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The initial gross cost basis capitalization currency amount paid to secure the asset unit",
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "depreciation_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The annual straight-line depreciation loss percentage scale parameter (e.g., 12.50 for 12.5% annualized decay)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The adjusted current net book value representing asset worth post-depreciation cycles",
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "warranty_expiry",
                    models.DateField(
                        blank=True,
                        help_text="The final contractual calendar coverage expiration date logged by the manufacturer warranty agreement",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "IN_USE",
                                "In Use - Asset is operational and deployed inside company workflows",
                            ),
                            (
                                "MAINTENANCE",
                                "Maintenance - Asset is offline undergoing technical service or workshop repair",
                            ),
                            (
                                "DISPOSED",
                                "Disposed - Asset is retired from accounting books via scrap sale or liquidation",
                            ),
                            (
                                "LOST",
                                "Lost - Asset is missing from physical audits; flagged for financial investigation",
                            ),
                            (
                                "TRANSFERRED",
                                "Transferred - Asset is locked mid-transit during relocation between operational branches",
                            ),
                        ],
                        db_index=True,
                        default="IN_USE",
                        help_text="The current active lifecycle pipeline phase state configuration tracking the hardware asset node",
                        max_length=30,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Granular physical damage tracking notes, audit log annotations, or liquidation justifications",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now,
                        help_text="Timezone-aware log record tracking exactly when this asset index joined the database system",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp tracking exactly when parameter attributes inside this inventory node mutated",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="The primary custodian employee or operational staff driver held personally accountable for this unit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_assets",
                        to="hr.employee",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="The physical corporate branch office or garage outpost currently storing or utilizing this item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="branches.branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant corporate node holding legal data sovereignty over this inventory asset record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="The generalized asset catalog categorization group managing this inventory node",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="assets.assetcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fixed Asset Record",
                "verbose_name_plural": "Fixed Asset Records",
                "db_table": "assets",
                "ordering": ["tenant_id", "code"],
            },
        ),
        migrations.CreateModel(
            name="StorageUnit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique system identifier text key assigned to this warehouse facility (e.g., KHO_LOGISTICS_Q5)",
                        max_length=30,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable descriptive title label identifying this physical stockroom location",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Granular physical details, operation hours, capacity restrictions, or logistical notes",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now,
                        help_text="Timezone-aware log record tracking exactly when this storage site was added to the platform",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp tracking exactly when parameter attributes inside this storage configuration node changed",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific regional corporate branch office or shipping station controlling this physical depot",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="storage_units",
                        to="branches.branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant corporate node holding legal data sovereignty over this inventory location cluster",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_units",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Storage Unit",
                "verbose_name_plural": "Inventory Storage Units",
                "db_table": "storage_units",
                "ordering": ["tenant_id", "code"],
            },
        ),
        migrations.AddConstraint(
            model_name="assetcategory",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uq_tenant_asset_category_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_tenant_asset_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["IN_USE", "MAINTENANCE", "DISPOSED", "LOST", "TRANSFERRED"],
                    )
                ),
                name="chk_asset_lifecycle_status_enum",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("purchase_price__gte", 0),
                    ("purchase_price__isnull", True),
                    _connector="OR",
                ),
                name="chk_asset_purchase_price_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("current_value__gte", 0),
                    ("current_value__isnull", True),
                    _connector="OR",
                ),
                name="chk_asset_current_value_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="storageunit",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_tenant_storage_unit_code"
            ),
        ),
    ]
