# Generated by Django 6.0.6 on 2026-07-07 02:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General - General application settings"),
                            ("PAYMENT", "Payment - Payment gateway configurations"),
                            ("SMS", "SMS - SMS provider settings"),
                            ("EMAIL", "Email - Email provider settings"),
                            ("BOOKING", "Booking - Booking system settings"),
                            ("PRINTING", "Printing - Printing configurations"),
                            ("NOTIFICATION", "Notification - Notification settings"),
                            ("SECURITY", "Security - Security settings"),
                            ("INTEGRATION", "Integration - Third-party integrations"),
                            ("CUSTOM", "Custom - Custom tenant settings"),
                        ],
                        db_index=True,
                        help_text="Configuration category",
                        max_length=60,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text='Configuration key (e.g., "stripe_secret_key")',
                        max_length=120,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Key must contain only lowercase letters, numbers, and underscores",
                                regex="^[a-z0-9_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True,
                        help_text="Configuration value (encrypted if is_encrypted=True)",
                        null=True,
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String - Simple text value"),
                            ("integer", "Integer - Integer number"),
                            ("boolean", "Boolean - True/False value"),
                            ("json", "JSON - JSON object/array"),
                            ("secret", "Secret - Encrypted sensitive value"),
                            ("text", "Text - Multi-line text"),
                        ],
                        default="string",
                        help_text="Type of configuration value",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable label for the configuration",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what this config does",
                        null=True,
                    ),
                ),
                (
                    "is_encrypted",
                    models.BooleanField(
                        default=False,
                        help_text="Value is encrypted (for sensitive data)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Configuration is exposed to frontend"
                    ),
                ),
                (
                    "is_readonly",
                    models.BooleanField(
                        default=False,
                        help_text="Configuration is read-only (locked in production)",
                    ),
                ),
                (
                    "env",
                    models.CharField(
                        choices=[
                            ("ALL", "All - Available in all environments"),
                            ("DEVELOPMENT", "Development - Development only"),
                            ("STAGING", "Staging - Staging only"),
                            ("PRODUCTION", "Production - Production only"),
                        ],
                        db_index=True,
                        default="ALL",
                        help_text="Environment where this config applies",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this configuration",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_configs",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this config",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Config",
                "verbose_name_plural": "System Configs",
                "db_table": "system_configs",
                "ordering": ["category", "key"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfigAuditLog",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create - Config created"),
                            ("UPDATE", "Update - Config modified"),
                            ("DELETE", "Delete - Config deleted"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_actions_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_config_audit_logs",
                        to="system_config.systemconfig",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_audit_logs",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Config Audit Log",
                "verbose_name_plural": "System Config Audit Logs",
                "db_table": "system_config_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfigHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "old_value",
                    models.TextField(
                        blank=True, help_text="Previous value before change", null=True
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, help_text="New value after change", null=True
                    ),
                ),
                (
                    "changed_by_username",
                    models.CharField(
                        blank=True,
                        help_text="Username snapshot at time of change",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for the change", null=True
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the change was made",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_history_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        help_text="Configuration that was changed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="system_config.systemconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Config History",
                "verbose_name_plural": "System Config Histories",
                "db_table": "system_config_history",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="systemconfig",
            index=models.Index(
                fields=["tenant", "category"], name="idx_config_tenant_category"
            ),
        ),
        migrations.AddIndex(
            model_name="systemconfig",
            index=models.Index(
                fields=["tenant", "is_public"], name="idx_config_tenant_public"
            ),
        ),
        migrations.AddIndex(
            model_name="systemconfig",
            index=models.Index(fields=["env"], name="idx_config_env"),
        ),
        migrations.AddConstraint(
            model_name="systemconfig",
            constraint=models.UniqueConstraint(
                fields=("tenant", "category", "key"),
                name="unique_tenant_category_key",
                violation_error_message="Config key must be unique within tenant and category",
            ),
        ),
        migrations.AddConstraint(
            model_name="systemconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "value_type__in",
                        ["string", "integer", "boolean", "json", "secret", "text"],
                    )
                ),
                name="chk_config_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="systemconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("env__in", ["ALL", "DEVELOPMENT", "STAGING", "PRODUCTION"])
                ),
                name="chk_config_env",
            ),
        ),
        migrations.AddIndex(
            model_name="systemconfigauditlog",
            index=models.Index(
                fields=["tenant", "created_at"], name="idx_conf_at_tenant_created"
            ),
        ),
        migrations.AddIndex(
            model_name="systemconfigauditlog",
            index=models.Index(
                fields=["config", "created_at"], name="idx_audit_config_created"
            ),
        ),
        migrations.AddIndex(
            model_name="systemconfighistory",
            index=models.Index(
                fields=["config", "changed_at"], name="idx_conf_his_conf_changed"
            ),
        ),
        migrations.AddIndex(
            model_name="systemconfighistory",
            index=models.Index(
                fields=["changed_by", "changed_at"], name="idx_conf_his_user_changed"
            ),
        ),
        migrations.AddIndex(
            model_name="systemconfighistory",
            index=models.Index(
                fields=["-changed_at"], name="idx_conf_his_changed_desc"
            ),
        ),
    ]
