# Generated by Django 6.0.5 on 2026-06-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='systemconfigauditlog',
            new_name='idx_audit_config_created',
            old_name=' v',
        ),
    ]
