# Generated by Django 6.0.6 on 2026-07-09 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of entity being commented on",
                        max_length=60,
                    ),
                ),
                (
                    "entity_id",
                    models.BigIntegerField(
                        db_index=True, help_text="ID of entity being commented on"
                    ),
                ),
                ("body", models.TextField(help_text="Comment text")),
                (
                    "is_internal",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Comment is internal (staff only)",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Comment is pinned to top",
                    ),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True, help_text="When comment was last edited", null=True
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who wrote this comment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent comment (for nested replies)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="comments.comment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "db_table": "comments",
                "ordering": ["-is_pinned", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"], name="idx_comments_entity"
                    ),
                    models.Index(
                        condition=models.Q(("parent_id__isnull", False)),
                        fields=["parent_id"],
                        name="idx_comments_parent",
                    ),
                    models.Index(fields=["is_internal"], name="idx_comments_internal"),
                    models.Index(fields=["is_pinned"], name="idx_comments_pinned"),
                    models.Index(fields=["author_id"], name="idx_comments_author"),
                ],
            },
        ),
    ]
