# Generated by Django 6.0.6 on 2026-06-18 03:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("tenants", "0001_initial"),
        ("trips", "0001_initial"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Global immutable UUIDv4 identifier string optimized for external API exposure frameworks",
                        unique=True,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="The full legal name coordinates of the passenger customer",
                        max_length=255,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="The primary contact mobile phone string sequence used for transaction and authentication logs",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number format specification is invalid",
                                regex="^\\+?[0-9\\s\\-]{7,20}$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Electronic mail endpoint reference utilized for dynamic receipt or ticket issuance dispatches",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        help_text="Government issued asset identity validation parameters (e.g., Citizen ID, Passport number)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Calendar birth date marker utilized in age-group price classification algorithms",
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        help_text="Demographic taxonomy identification context gender indicator metadata",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="The formal dynamic physical localized living residence reference context text",
                        null=True,
                    ),
                ),
                (
                    "loyalty_points",
                    models.IntegerField(
                        default=0,
                        help_text="Cumulative arithmetic currency ledger balance accumulated through successful corporate booking cycles",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard - Entry baseline customer level"),
                            ("SILVER", "Silver - Intermediate tier level"),
                            ("GOLD", "Gold - High-value frequent rider level"),
                            ("PLATINUM", "Platinum - Premium elite status level"),
                        ],
                        db_index=True,
                        default="STANDARD",
                        help_text="The classification segmentation tier evaluating customer priority metrics ranking matrices",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "COUNTER",
                                "Counter - Offline terminal ticket counter registration",
                            ),
                            (
                                "ONLINE",
                                "Online - Consumer web or mobile application portal",
                            ),
                            (
                                "AGENT",
                                "Agent - Third-party commercial travel agency system",
                            ),
                            (
                                "IMPORT",
                                "Import - Administrative spreadsheet or legacy DB data migration",
                            ),
                        ],
                        db_index=True,
                        default="COUNTER",
                        help_text="The primary customer onboarding ingestion origin channel context metric token",
                        max_length=30,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Miscellaneous service notes, wheelchair requirements, allergy alerts, or loyalty exemptions log",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant owner who maintains ownership of this customer CRM identity profile",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Profile",
                "verbose_name_plural": "Customer Profiles",
                "db_table": "customers",
                "ordering": ["-created_at", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="GroupContract",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "contract_code",
                    models.CharField(
                        help_text="Unique business reference ledger code tracking this contract sheet (e.g., CTR-2026-001X)",
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Contract code must contain only uppercase letters, numbers, hyphens, and underscores",
                                regex="^[A-Z0-9\\-_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        help_text="Full legal individual name or corporate company text purchasing this block contract",
                        max_length=255,
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        help_text="Primary communication phone sequence used for B2B accounts follow-up operations",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Customer contact phone number format specification is invalid",
                                regex="^\\+?[0-9\\s\\-]{7,20}$",
                            )
                        ],
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        help_text="Electronic mail node endpoint used for automatic billing and invoice dispatch lines",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "customer_tax_code",
                    models.CharField(
                        blank=True,
                        help_text="Government statutory tax identifier token for corporate legal receipt generation (VAT invoice)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "seat_count",
                    models.SmallIntegerField(
                        help_text="Total aggregate allocation number of physical seat inventory chunks reserved by the group",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The full negotiated gross contract value currency rate calculated for this contract line",
                        max_digits=15,
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The initialization payment threshold required to transition the document out of Draft status",
                        max_digits=15,
                    ),
                ),
                (
                    "deposit_paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware timestamp logging exactly when database confirmed receipt of deposit funds",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "DRAFT",
                                "Draft - Negotiation planning phase, loose allocation hold",
                            ),
                            (
                                "CONFIRMED",
                                "Confirmed - Deposit cleared, passenger block inventory secured",
                            ),
                            (
                                "CANCELLED",
                                "Cancelled - Contract terminated, seat allocation blocks released",
                            ),
                            (
                                "COMPLETED",
                                "Completed - Journey finalized, invoice balances cleared and locked",
                            ),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="The structural workflow state tracking this B2B lease through settlement and execution gates",
                        max_length=30,
                    ),
                ),
                (
                    "contract_file",
                    models.CharField(
                        blank=True,
                        help_text="Cloud object storage URL file path string pointing to the digital scan copy of the signed contract PDF file",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Miscellaneous business negotiation notes, special pickup itineraries, or specific refund exemption logs",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The sales agent or corporate account manager who generated this document ledger line",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant corporate owner who holds commercial rights over this group charter ledger",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_contracts",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        help_text="The destination commercial trip vehicle journey assigned for this group booking",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_contracts",
                        to="trips.trip",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Contract",
                "verbose_name_plural": "Group Contracts",
                "db_table": "group_contracts",
                "ordering": ["-created_at", "contract_code"],
            },
        ),
        migrations.CreateModel(
            name="TicketBooking",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "booking_code",
                    models.CharField(
                        help_text="Unique human-readable ticketing code index used for customer reservation validation (e.g., PNR-9982X)",
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Booking code must contain only uppercase alphanumeric characters, hyphens, and underscores",
                                regex="^[A-Z0-9\\-_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            (
                                "COUNTER",
                                "Counter - Physical offline ticketing desk office",
                            ),
                            (
                                "ONLINE",
                                "Online - Consumer desktop web platform checkout",
                            ),
                            (
                                "AGENT",
                                "Agent - Third-party travel agency portal application",
                            ),
                            (
                                "MOBILE_APP",
                                "Mobile App - Native consumer smartphone software application",
                            ),
                            (
                                "B2B",
                                "B2B - Corporate affiliate API integration gateway connection",
                            ),
                        ],
                        db_index=True,
                        default="COUNTER",
                        help_text="The distribution sales channel pipeline through which this transaction entered the system",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "PENDING",
                                "Pending - Seat held, awaiting financial transaction clearance",
                            ),
                            (
                                "CONFIRMED",
                                "Confirmed - Ticket active, inventory assigned and validated",
                            ),
                            (
                                "CANCELLED",
                                "Cancelled - Aborted reservation, inventory released back to pool",
                            ),
                            (
                                "REFUNDED",
                                "Refunded - Voided with commercial banking reversal executed",
                            ),
                            (
                                "NO_SHOW",
                                "No Show - Trip departed, passenger failed check-in gates",
                            ),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="The core transactional stage tracking this reservation lifecycle step sequence",
                        max_length=30,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The gross commercial price balance calculated for this entire ticket booking sheet",
                        max_digits=15,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The total cash/digital ledger values successfully cleared and captured for this invoice",
                        max_digits=15,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Miscellaneous customer preferences notes, specific wheelchair alerts, or manual audit details",
                        null=True,
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware timestamp logging exactly when this ticket profile was aborted",
                        null=True,
                    ),
                ),
                (
                    "cancel_reason",
                    models.TextField(
                        blank=True,
                        help_text="Explicit text statement provided explaining why this ticket reservation was aborted",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware ticket hold duration window boundary. If payment drops past this, hold voids automatically",
                        null=True,
                    ),
                ),
                (
                    "booked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The corporate system user account who executed or processed this sale profile",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="The physical branch office station hub where this booking transaction was logged",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="branch_bookings",
                        to="branches.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="The customer asset or primary passenger lodging this transaction sheet",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="customers_tickets.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant corporate owner who holds rights over this transactional booking ledger",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_bookings",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        help_text="The active physical commercial trip journey line assigned under this ticket",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="trips.trip",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Booking",
                "verbose_name_plural": "Ticket Bookings",
                "db_table": "ticket_bookings",
                "ordering": ["-created_at", "booking_code"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "seat_code",
                    models.CharField(
                        blank=True,
                        help_text="Immutable string copy snapshot of the seat code (e.g., A12, B04) to prevent historic data loss",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "passenger_name",
                    models.CharField(
                        blank=True,
                        help_text="Full name coordinates of the physical individual traveling on this seat pass",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "passenger_phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact mobile string sequence belonging specifically to the passenger assigned to this seat",
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Passenger phone number format specification is invalid",
                                regex="^\\+?[0-9\\s\\-]{7,20}$",
                            )
                        ],
                    ),
                ),
                (
                    "passenger_type",
                    models.CharField(
                        choices=[
                            ("ADULT", "Adult - Standard age passenger pricing rate"),
                            ("CHILD", "Child - Concessionary minor age pricing rate"),
                            ("INFANT", "Infant - Toddler or lap child allocation"),
                            (
                                "STUDENT",
                                "Student - Subsidized educational qualification tier",
                            ),
                            ("SENIOR", "Senior - Subsidized elderly citizen tier"),
                        ],
                        db_index=True,
                        default="ADULT",
                        help_text="The demographic price calculation category class mapped to this passenger",
                        max_length=20,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The unmodified standard entry-level price allocated for this seat routing specification",
                        max_digits=15,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The total deducted monetary value derived from promotional voucher campaigns or concession tiers",
                        max_digits=15,
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The actual final commercial revenue collected for this specific seat item (base_price - discount_amount)",
                        max_digits=15,
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(
                        blank=True,
                        help_text="Cryptographically unique text token string rendered into QR graphic matrix blocks for mobile phone scanning",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        help_text="Cryptographically unique text token string rendered into physical 1D barcode layouts for printed thermal stubs",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "ACTIVE",
                                "Active - Valid ticket, open for terminal boarding gates",
                            ),
                            (
                                "USED",
                                "Used - Boarding complete, passenger inside vehicle",
                            ),
                            (
                                "CANCELLED",
                                "Cancelled - Aborted ticket, seat returned to pool",
                            ),
                            (
                                "REFUNDED",
                                "Refunded - Terminated with processed banking financial reversal",
                            ),
                            (
                                "EXCHANGED",
                                "Exchanged - Voided due to seat/trip reassignment modification",
                            ),
                            (
                                "EXPIRED",
                                "Expired - Journey departed, passenger missed check-in window",
                            ),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        help_text="The current functional stage state tracking this boarding pass ticket asset",
                        max_length=30,
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware timestamp logging exactly when the customer successfully cleared bến bãi checkpoint gates",
                        null=True,
                    ),
                ),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The terminal controller or conductor user who scanned and cleared this ticket at the gate",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_ticket_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        blank=True,
                        help_text="The physical asset seat coordinate row currently assigned inside the vehicle model",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="vehicles.seat",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        help_text="The parent transactional ledger configuration header mapping this ticket asset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="customers_tickets.ticketbooking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passenger Ticket",
                "verbose_name_plural": "Passenger Tickets",
                "db_table": "tickets",
                "ordering": ["booking", "seat_code", "id"],
            },
        ),
        migrations.CreateModel(
            name="TicketExchange",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "exchange_code",
                    models.CharField(
                        help_text="Unique operational index token used for tracking outbound modification vouchers (e.g., EXC-9921-X)",
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Exchange voucher code must contain only uppercase letters, numbers, hyphens, and underscores",
                                regex="^[A-Z0-9\\-_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Explicit text statement provided explaining why the customer requested a route mutation",
                        null=True,
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The administrative surcharge penalty penalty assessed for processing the ticket modification",
                        max_digits=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "PENDING",
                                "Pending - Rerouting initialized, awaiting fee payment settlement",
                            ),
                            (
                                "COMPLETED",
                                "Completed - Fee cleared, original ticket revoked, new ticket activated",
                            ),
                            (
                                "REJECTED",
                                "Rejected - Exchange request cancelled, original ticket state retained",
                            ),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="The progression phase state tracking this swap log through verification and payment gates",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "new_ticket",
                    models.ForeignKey(
                        blank=True,
                        help_text="The newly minted replacement boarding pass ticket issued under this mutation pipeline",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exchange_as_new",
                        to="customers_tickets.ticket",
                    ),
                ),
                (
                    "original_ticket",
                    models.ForeignKey(
                        help_text="The historical core passenger boarding pass targeted to be revoked and replaced",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exchange_as_original",
                        to="customers_tickets.ticket",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The ticket box clerk or helpdesk user account executing this rerouting transition",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_exchanges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Exchange Ledger",
                "verbose_name_plural": "Ticket Exchange Ledgers",
                "db_table": "ticket_exchanges",
                "ordering": ["-created_at", "exchange_code"],
            },
        ),
        migrations.CreateModel(
            name="TicketRefund",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "refund_code",
                    models.CharField(
                        help_text="Unique commercial index token used for tracking outbound financial vouchers (e.g., REF-9921-X)",
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Refund voucher code must contain only uppercase letters, numbers, hyphens, and underscores",
                                regex="^[A-Z0-9\\-_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Contextual justification annotations explaining why this specific ticket was voided",
                        null=True,
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The net collected revenue amount paid originally for the ticket seat line",
                        max_digits=15,
                    ),
                ),
                (
                    "penalty_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The cancellation administrative fee penalty deducted from the client balance based on timeline policies",
                        max_digits=15,
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The exact ultimate payout capital cash sum returned back to the consumer (original_amount - penalty_amount)",
                        max_digits=15,
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "CASH",
                                "Cash - Handed directly at physical counter terminal drawers",
                            ),
                            (
                                "BANK_TRANSFER",
                                "Bank Transfer - Electronic wire reversal processing",
                            ),
                            (
                                "WALLET",
                                "Wallet - E-Wallet partner integration API gateway return",
                            ),
                            (
                                "CREDIT",
                                "Credit - Virtual internal wallet voucher points issued",
                            ),
                        ],
                        db_index=True,
                        help_text="The target liquidation path used to route the outgoing capital back to the customer",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "PENDING",
                                "Pending - Review pipeline active, awaiting manager validation",
                            ),
                            (
                                "APPROVED",
                                "Approved - Clearance authorized, payout transactional task queued",
                            ),
                            (
                                "COMPLETED",
                                "Completed - Capital successfully transferred, ledger locked",
                            ),
                            (
                                "REJECTED",
                                "Rejected - Request declined, booking ticket restored to active status",
                            ),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="The structural state mapping this liquidation voucher through review and payout channels",
                        max_length=20,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware timestamp logging exactly when final completion or rejection was executed",
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The supervisor or station manager validating and granting commercial clearance sign-off",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorized_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff accountant or agent counter employee who initiated this liquidation line",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        help_text="The specific boarding pass ticket identity sheet being processed for liquidation",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_records",
                        to="customers_tickets.ticket",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Refund Ledger",
                "verbose_name_plural": "Ticket Refund Ledgers",
                "db_table": "ticket_refunds",
                "ordering": ["-created_at", "refund_code"],
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "tier", "full_name"],
                name="idx_crm_tenant_tier_search",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("tenant", "phone"), name="unique_tenant_customer_phone"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tier__in", ["STANDARD", "SILVER", "GOLD", "PLATINUM"])
                ),
                name="chk_customer_loyalty_tier",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source__in", ["COUNTER", "ONLINE", "AGENT", "IMPORT"])
                ),
                name="chk_customer_ingestion_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                condition=models.Q(("loyalty_points__gte", 0)),
                name="chk_customer_loyalty_points_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["DRAFT", "CONFIRMED", "CANCELLED", "COMPLETED"])
                ),
                name="chk_group_contract_status_rules",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("total_amount__gte", 0), ("deposit_amount__gte", 0)
                ),
                name="chk_contract_amounts_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(("deposit_amount__lte", models.F("total_amount"))),
                name="chk_contract_deposit_limit",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketbooking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["PENDING", "CONFIRMED", "CANCELLED", "REFUNDED", "NO_SHOW"],
                    )
                ),
                name="chk_booking_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketbooking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("channel__in", ["COUNTER", "ONLINE", "AGENT", "MOBILE_APP", "B2B"])
                ),
                name="chk_booking_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketbooking",
            constraint=models.CheckConstraint(
                condition=models.Q(("paid_amount__gte", 0), ("total_amount__gte", 0)),
                name="chk_booking_amounts_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                condition=models.Q(("qr_code__isnull", False)),
                fields=["qr_code"],
                name="idx_tickets_qr_partial",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "ACTIVE",
                            "USED",
                            "CANCELLED",
                            "REFUNDED",
                            "EXCHANGED",
                            "EXPIRED",
                        ],
                    )
                ),
                name="chk_ticket_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("final_price__gte", 0),
                    ("base_price__gte", 0),
                    ("discount_amount__gte", 0),
                ),
                name="chk_ticket_prices_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketexchange",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["PENDING", "COMPLETED", "REJECTED"])
                ),
                name="chk_exchange_status_rules",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketexchange",
            constraint=models.CheckConstraint(
                condition=models.Q(("fee__gte", 0)), name="chk_exchange_fee_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketrefund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["PENDING", "APPROVED", "COMPLETED", "REJECTED"])
                ),
                name="chk_refund_status_rules",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketrefund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("original_amount__gte", 0),
                    ("penalty_amount__gte", 0),
                    ("refund_amount__gte", 0),
                ),
                name="chk_refund_amounts_positive",
            ),
        ),
    ]
