# Generated by Django 6.0.5 on 2026-06-02 13:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Province code (e.g., HN, HCM, DN)",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code must contain only uppercase letters and numbers",
                                regex="^[A-Z0-9]+$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(help_text="Province name", max_length=100)),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NORTH", "North - Northern region"),
                            ("CENTRAL", "Central - Central region"),
                            ("SOUTH", "South - Southern region"),
                        ],
                        db_index=True,
                        help_text="Geographic region",
                        max_length=30,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
                "db_table": "provinces",
                "ordering": ["region", "name"],
                "indexes": [
                    models.Index(fields=["region"], name="idx_province_region"),
                    models.Index(fields=["code"], name="idx_province_code"),
                ],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="District code",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code must contain only uppercase letters and numbers",
                                regex="^[A-Z0-9]+$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(help_text="District name", max_length=100)),
                (
                    "province",
                    models.ForeignKey(
                        help_text="Province this district belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="routes.province",
                    ),
                ),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "db_table": "districts",
                "ordering": ["province", "name"],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique route code per tenant (e.g., HN-SGN-01)",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code must contain only uppercase letters, numbers, hyphens, and underscores",
                                regex="^[A-Z0-9\\-_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name of the route", max_length=255
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Route distance in kilometers",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "duration_min",
                    models.IntegerField(
                        blank=True,
                        help_text="Estimated travel duration in minutes",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this route is active and operational",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the route was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the route was last updated",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant owner of this route",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
                "db_table": "routes",
                "ordering": ["tenant", "code"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("departure_time", models.TimeField(help_text="Departure time")),
                ("arrival_time", models.TimeField(help_text="Arrival time")),
                (
                    "capacity",
                    models.IntegerField(default=50, help_text="Vehicle capacity"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Schedule is active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When schedule was created",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        help_text="Route for this schedule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule",
                "verbose_name_plural": "Schedules",
                "db_table": "schedules",
                "ordering": ["route", "departure_time"],
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique station code (e.g., HN_MAIN, SGN_WEST)",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code must contain only uppercase letters, numbers, and underscores",
                                regex="^[A-Z0-9_]+$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(help_text="Station name", max_length=255)),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Full address of station", null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Latitude coordinate",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Longitude coordinate",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Station phone number",
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid phone number format",
                                regex="^\\+?[0-9\\-\\(\\)\\s]+$",
                            )
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Station is active and operational",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When station was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When station was last updated"
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        help_text="Province where station is located",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="routes.province",
                    ),
                ),
            ],
            options={
                "verbose_name": "Station",
                "verbose_name_plural": "Stations",
                "db_table": "stations",
                "ordering": ["province", "name"],
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "stop_order",
                    models.PositiveSmallIntegerField(
                        help_text="Sequence order of this stop within the route (starts from 1)"
                    ),
                ),
                (
                    "arrive_offset_min",
                    models.IntegerField(
                        blank=True,
                        help_text="Arrival time offset in minutes from route start time",
                        null=True,
                    ),
                ),
                (
                    "depart_offset_min",
                    models.IntegerField(
                        blank=True,
                        help_text="Departure time offset in minutes from route start time",
                        null=True,
                    ),
                ),
                (
                    "pickup_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether passengers can board at this station",
                    ),
                ),
                (
                    "dropoff_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether passengers can alight at this station",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        help_text="Route this stop belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="routes.route",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        help_text="Station where the route stops",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="route_stops",
                        to="routes.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route Stop",
                "verbose_name_plural": "Route Stops",
                "db_table": "route_stops",
                "ordering": ["route", "stop_order"],
            },
        ),
        migrations.AddField(
            model_name="route",
            name="destination",
            field=models.ForeignKey(
                help_text="Ending station of the route",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="destination_routes",
                to="routes.station",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="origin",
            field=models.ForeignKey(
                help_text="Starting station of the route",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="origin_routes",
                to="routes.station",
            ),
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Ward code",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code must contain only uppercase letters and numbers",
                                regex="^[A-Z0-9]+$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(help_text="Ward name", max_length=100)),
                (
                    "district",
                    models.ForeignKey(
                        help_text="District this ward belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wards",
                        to="routes.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ward",
                "verbose_name_plural": "Wards",
                "db_table": "wards",
                "ordering": ["district", "name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Location name", max_length=200)),
                (
                    "address",
                    models.CharField(help_text="Street address", max_length=500),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("OFFICE", "Office - Office location"),
                            ("WAREHOUSE", "Warehouse - Warehouse location"),
                            ("PICKUP", "Pickup - Pickup point"),
                            ("DELIVERY", "Delivery - Delivery point"),
                            ("BRANCH", "Branch - Branch office"),
                            ("CUSTOM", "Custom - Custom location"),
                        ],
                        db_index=True,
                        default="CUSTOM",
                        help_text="Type of location",
                        max_length=30,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When location was created",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        help_text="Ward this location is in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="routes.ward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "db_table": "locations",
                "ordering": ["ward", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="district",
            index=models.Index(fields=["province"], name="idx_district_province"),
        ),
        migrations.AddConstraint(
            model_name="district",
            constraint=models.UniqueConstraint(
                fields=("province", "code"), name="unique_province_district_code"
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["route"], name="idx_schedule_route"),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["departure_time"], name="idx_schedule_departure"
            ),
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(fields=["province"], name="idx_station_province"),
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(fields=["is_active"], name="idx_station_active"),
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(fields=["code"], name="idx_station_code"),
        ),
        migrations.AddIndex(
            model_name="routestop",
            index=models.Index(
                fields=["route", "stop_order"], name="idx_route_stop_sequence"
            ),
        ),
        migrations.AddIndex(
            model_name="routestop",
            index=models.Index(fields=["station"], name="idx_stop_station_lookup"),
        ),
        migrations.AddConstraint(
            model_name="routestop",
            constraint=models.UniqueConstraint(
                fields=("route", "stop_order"), name="unique_route_stop_order"
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["tenant", "is_active"], name="idx_route_tenant_active"
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(fields=["origin", "destination"], name="idx_route_path"),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="unique_tenant_route_code"
            ),
        ),
        migrations.AddIndex(
            model_name="ward",
            index=models.Index(fields=["district"], name="idx_ward_district"),
        ),
        migrations.AddConstraint(
            model_name="ward",
            constraint=models.UniqueConstraint(
                fields=("district", "code"), name="unique_district_ward_code"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["ward"], name="idx_location_ward"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["location_type"], name="idx_location_type"),
        ),
    ]
