# Generated by Django 6.0.6 on 2026-07-07 02:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Official name of the department (e.g., Human Resources, Accounting)",
                        max_length=100,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff account designated as the head/manager of this division",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant owner of this department corporate division",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "departments",
                "ordering": ["tenant", "name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique business identifier system code (e.g., EMP-2026-09)",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code must contain only uppercase letters, numbers, hyphens, and underscores",
                                regex="^[A-Z0-9\\-_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Official full legal name of the employee",
                        max_length=255,
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        help_text="National identity card or citizenship passport index (e.g., CCCD)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary mobile or telecommunication entry node",
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid phone format",
                                regex="^\\+?[0-9\\s.\\-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        help_text="Corporate or personal communication contact mailbox address",
                        max_length=244,
                        null=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Official birth record calendar date",
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Biological or legal identity gender profile token",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Current residential or permanent accommodation address",
                        null=True,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("DRIVER", "Driver - Fleet vehicle operator"),
                            ("ASSISTANT", "Assistant - Trip conductor crew"),
                            ("CASHIER", "Cashier - Ticket collection staff"),
                            ("DISPATCHER", "Dispatcher - Trip operations coordinator"),
                            ("ACCOUNTANT", "Accountant - Financial staff"),
                            ("MANAGER", "Manager - General leadership line"),
                            ("OTHER", "Other - Custom staff classification"),
                        ],
                        db_index=True,
                        help_text="Active job role designation within operational flows",
                        max_length=100,
                    ),
                ),
                (
                    "hired_at",
                    models.DateField(
                        help_text="Calendar date when employment officially commenced"
                    ),
                ),
                (
                    "terminated_at",
                    models.DateField(
                        blank=True,
                        help_text="Calendar date when employment contract was formally ended",
                        null=True,
                    ),
                ),
                (
                    "termination_reason",
                    models.TextField(
                        blank=True,
                        help_text="Internal exit log detailing background factors for termination",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Designates whether this employee is currently working and on the active payroll",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        help_text="Commercial vehicle driving license identifier token number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "license_class",
                    models.CharField(
                        blank=True,
                        help_text="Driving license category tier classification (e.g., B2, C, D, E, FC)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "license_expiry",
                    models.DateField(
                        blank=True,
                        help_text="Driving license legal validation expiry date threshold",
                        null=True,
                    ),
                ),
                (
                    "social_insurance_no",
                    models.CharField(
                        blank=True,
                        help_text="State-managed social insurance registry profile book identification code",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "health_insurance_no",
                    models.CharField(
                        blank=True,
                        help_text="National health care safety insurance policy tracking index",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "tax_code",
                    models.CharField(
                        blank=True,
                        help_text="Personal income tax individual registration index number (PIT)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True,
                        help_text="Bank routing ledger account identity number for salary wire disbursements",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        help_text="Official institutional commercial bank corporate name",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "emergency_contact",
                    models.JSONField(
                        default=dict,
                        help_text="Complex data object capturing name, kinship relation, phone node array for accidents",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Physical home branch or hub where staff reports to work",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="branches.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Corporate organizational department division mapping",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="hr.department",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant owner of this employee record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "user_account",
                    models.OneToOneField(
                        blank=True,
                        help_text="Associated system user credentials for dashboard and portal login permissions",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "db_table": "employees",
                "ordering": ["tenant", "-is_active", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual - Paid Vacation Time"),
                            ("SICK", "Sick - Medical/Health Absence"),
                            ("UNPAID", "Unpaid - Non-compensated Leave"),
                            ("MATERNITY", "Maternity - Statutory Parental Leave"),
                            (
                                "COMPASSIONATE",
                                "Compassionate - Special/Bereavement Leave",
                            ),
                        ],
                        db_index=True,
                        help_text="Classification category determining compensation and matrix handling",
                        max_length=30,
                    ),
                ),
                (
                    "from_date",
                    models.DateField(
                        help_text="The inclusive starting calendar date bound for the leave duration window"
                    ),
                ),
                (
                    "to_date",
                    models.DateField(
                        help_text="The inclusive ending calendar date bound for the leave duration window"
                    ),
                ),
                (
                    "days_count",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Calculated fractional decimal metric totaling net absences (e.g., 0.5 for half day)",
                        max_digits=4,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Contextual statement provided by applicant explaining absence requirements",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending - Awaiting Review"),
                            ("APPROVED", "Approved - Authorized and Confirmed"),
                            ("REJECTED", "Rejected - Declined by Reviewer"),
                            ("CANCELLED", "Cancelled - Withdrawn by Employee"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Workflow progression state measuring administrative review status",
                        max_length=20,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware timestamp logging exactly when authorization occurred",
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The administrative management account signing off on this decision profile",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="The employee asset lodging this time-off request application",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
                "db_table": "leave_requests",
                "ordering": ["-created_at", "employee"],
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "period_year",
                    models.PositiveSmallIntegerField(
                        help_text="The specific calendar tracking year for this payment cycle (e.g., 2026)"
                    ),
                ),
                (
                    "period_month",
                    models.PositiveSmallIntegerField(
                        help_text="The specific calendar tracking month for this payment cycle (1 to 12)"
                    ),
                ),
                (
                    "working_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        help_text="Total cumulative productive attendance days logged in the current cycle month",
                        max_digits=4,
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Contractual fixed base salary allocated for the standard cycle period",
                        max_digits=15,
                    ),
                ),
                (
                    "allowances",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total standard recurring allowances (e.g., lunch, fuel, phone support)",
                        max_digits=15,
                    ),
                ),
                (
                    "overtime_pay",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total accrued compensation generated from approved overtime working hour shifts",
                        max_digits=15,
                    ),
                ),
                (
                    "bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Discretionary performance bonuses, commissions, or milestone incentives",
                        max_digits=15,
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Standard internal deductions (e.g., disciplinary fines, asset damages, advanced payroll draws)",
                        max_digits=15,
                    ),
                ),
                (
                    "insurance_deduct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Employee-borne statutory social, health, and unemployment insurance co-pay withholding",
                        max_digits=15,
                    ),
                ),
                (
                    "tax_deduct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Calculated Personal Income Tax (PIT) withholding value scheduled for state treasury remittance",
                        max_digits=15,
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The definitive final take-home net earnings payable to the employee after arithmetic reduction rules",
                        max_digits=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "DRAFT",
                                "Draft - Statement under review or recalculation",
                            ),
                            (
                                "APPROVED",
                                "Approved - Verified by management, locked for payout",
                            ),
                            ("PAID", "Paid - Fund disbursement successfully executed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="The workflow stage representing review pipeline status tracking",
                        max_length=20,
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware timestamp logging exactly when financial bank wire transaction occurred",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal auditing annotations explaining specific modifications, tax exceptions, or formulas",
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The financial or HR authority account signing off on this statement line",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payrolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="The employee asset whose monthly earnings are calculated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrolls",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll",
                "verbose_name_plural": "Payrolls",
                "db_table": "payroll",
                "ordering": ["-period_year", "-period_month", "employee"],
            },
        ),
        migrations.CreateModel(
            name="ShiftType",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique operational shift code identifier per tenant (e.g., MORNING, NIGHT_01)",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code must contain only uppercase letters, numbers, hyphens, and underscores",
                                regex="^[A-Z0-9\\-_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human readable display name of the shift schedule pattern",
                        max_length=100,
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="The official clock time when the work shift begins"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        help_text="The official clock time when the work shift ends"
                    ),
                ),
                (
                    "is_overnight",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the shift boundary spans across midnight (e.g., 22:00 to 06:00 next day)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant owner of this operational shift type configuration",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_types",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift Type",
                "verbose_name_plural": "Shift Types",
                "db_table": "shift_types",
                "ordering": ["tenant", "start_time", "code"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "work_date",
                    models.DateField(
                        db_index=True,
                        help_text="The targeted calendar date context for this schedule log entry",
                    ),
                ),
                (
                    "check_in",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware timestamp capturing the exact check-in puncture",
                        null=True,
                    ),
                ),
                (
                    "check_out",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware timestamp capturing the exact check-out puncture",
                        null=True,
                    ),
                ),
                (
                    "check_in_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="High-precision GPS latitude coordinate parsed at check-in node",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "check_in_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="High-precision GPS longitude coordinate parsed at check-in node",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present - Full day completed"),
                            ("ABSENT", "Absent - Missing shift"),
                            ("LATE", "Late - Clocked in past shift start time"),
                            ("HALF_DAY", "Half Day - Partial shift attendance"),
                            ("LEAVE", "Leave - Approved dynamic day off"),
                            (
                                "HOLIDAY",
                                "Holiday - Scheduled public or corporate holiday",
                            ),
                        ],
                        db_index=True,
                        default="PRESENT",
                        help_text="Operational status classifying compliance of the logging day metrics",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Annotations detailing late reasons, geo-location errors, or adjustments",
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The administrative authority account signing off or adjusting this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="The employee asset profile this log sheet maps to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="hr.employee",
                    ),
                ),
                (
                    "shift_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="The planned working timeframe configuration target schema",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendances",
                        to="hr.shifttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendances",
                "db_table": "attendances",
                "ordering": ["-work_date", "employee"],
            },
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["tenant", "name"], name="idx_dept_tenant_name_lookup"
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="unique_tenant_department_name"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["branch", "is_active", "position"],
                name="idx_emp_branch_dispatch",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["license_expiry"], name="idx_emp_license_compliance"
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="unique_tenant_employee_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                condition=models.Q(("gender__in", ["MALE", "FEMALE", "OTHER"])),
                name="chk_employee_gender",
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["status", "-created_at"], name="idx_leave_review_pipeline"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["from_date", "to_date"], name="idx_leave_calendar_window"
            ),
        ),
        migrations.AddConstraint(
            model_name="leaverequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "leave_type__in",
                        ["ANNUAL", "SICK", "UNPAID", "MATERNITY", "COMPASSIONATE"],
                    )
                ),
                name="chk_leave_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaverequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["PENDING", "APPROVED", "REJECTED", "CANCELLED"])
                ),
                name="chk_leave_status",
            ),
        ),
        migrations.AddIndex(
            model_name="payroll",
            index=models.Index(
                fields=["period_year", "period_month", "status"],
                name="idx_pay_period_status_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="payroll",
            constraint=models.UniqueConstraint(
                fields=("employee", "period_year", "period_month"),
                name="unique_employee_payroll_period",
            ),
        ),
        migrations.AddIndex(
            model_name="shifttype",
            index=models.Index(
                fields=["tenant", "start_time", "end_time"],
                name="idx_shift_timeline_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="shifttype",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="unique_tenant_shift_type_code"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["work_date", "status"], name="idx_att_date_status_metrics"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("employee", "work_date"), name="unique_employee_work_date"
            ),
        ),
    ]
