from rest_framework import serializers


class TenantResponseSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    uuid = serializers.CharField()
    code = serializers.CharField()
    name = serializers.CharField()
    plan = serializers.CharField()
    is_active = serializers.BooleanField()
    currency = serializers.CharField()
    exchange_rate = serializers.DecimalField(max_digits=12, decimal_places=4)
    default_language = serializers.CharField()
    timezone = serializers.CharField()
    primary_color = serializers.CharField()
    max_users = serializers.IntegerField()
    max_branches = serializers.IntegerField()
    max_vehicles = serializers.IntegerField()
    subscription_started_at = serializers.DateTimeField(allow_null=True)
    subscription_expires_at = serializers.DateTimeField(allow_null=True)
    settings = serializers.DictField()
    domain = serializers.CharField(allow_null=True)
    logo_url = serializers.CharField(allow_null=True)
    created_at = serializers.DateTimeField(allow_null=True)
    updated_at = serializers.DateTimeField(allow_null=True)
