# Generated by Django 6.0.6 on 2026-07-09 03:50

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for external API calls",
                        unique=True,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Unique username per tenant",
                        max_length=150,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Username can only contain letters, numbers, dots, underscores, and hyphens",
                                regex="^[a-zA-Z0-9._-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Unique email per tenant",
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="Hashed password (PBKDF2)", max_length=255
                    ),
                ),
                (
                    "full_name",
                    models.CharField(help_text="User full name", max_length=255),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="User phone number",
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid phone number format",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "avatar",
                    models.URLField(
                        blank=True,
                        help_text="URL to user avatar image",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="User account is active"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, help_text="User can access admin interface"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False, help_text="User has all permissions"
                    ),
                ),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=False,
                        help_text="User must change password on next login",
                    ),
                ),
                (
                    "last_password_change",
                    models.DateTimeField(
                        blank=True,
                        help_text="When password was last changed",
                        null=True,
                    ),
                ),
                (
                    "password_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When password expires (null = never)",
                        null=True,
                    ),
                ),
                (
                    "two_fa_enabled",
                    models.BooleanField(
                        default=False, help_text="Two-factor authentication is enabled"
                    ),
                ),
                (
                    "two_fa_secret",
                    models.CharField(
                        blank=True,
                        help_text="TOTP secret for 2FA (encrypted in production)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "two_fa_backup_codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Backup codes for 2FA recovery",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful login timestamp",
                        null=True,
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of last login", null=True
                    ),
                ),
                (
                    "failed_login_count",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Number of consecutive failed login attempts",
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Account locked until this time (null = not locked)",
                        null=True,
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User UI preferences (theme, language, etc.)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "User Account",
                "verbose_name_plural": "User Accounts",
                "db_table": "user_accounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Username snapshot at time of action",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create - New object created"),
                            ("UPDATE", "Update - Object modified"),
                            ("DELETE", "Delete - Object deleted"),
                            ("LOGIN", "Login - User logged in"),
                            ("LOGOUT", "Logout - User logged out"),
                            ("EXPORT", "Export - Data exported"),
                            ("IMPORT", "Import - Data imported"),
                            ("APPROVE", "Approve - Action approved"),
                            ("REJECT", "Reject - Action rejected"),
                            ("BULK_UPDATE", "Bulk Update - Multiple objects updated"),
                            ("BULK_DELETE", "Bulk Delete - Multiple objects deleted"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        db_index=True,
                        help_text='Module name (e.g., "tickets", "vehicles", "hr")',
                        max_length=100,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True,
                        help_text='Type of object affected (e.g., "Ticket", "Vehicle")',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the object affected",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "object_repr",
                    models.TextField(
                        blank=True,
                        help_text="String representation of the object",
                        null=True,
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, help_text="Previous values before change", null=True
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, help_text="New values after change", null=True
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, help_text="Summary of changes made", null=True
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the request", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent string", null=True
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Correlation ID for tracking related operations",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLogArchive",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("audit_data", models.JSONField(help_text="Complete audit log data")),
                (
                    "original_id",
                    models.BigIntegerField(
                        help_text="Original audit log ID", unique=True
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this log was archived"
                    ),
                ),
                (
                    "archived_by_id",
                    models.IntegerField(
                        blank=True, help_text="User who archived this log", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Archive",
                "verbose_name_plural": "Audit Log Archives",
                "db_table": "audit_logs_archive",
                "ordering": ["-archived_at"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Reset token (one-time use)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("expires_at", models.DateTimeField(help_text="Token expiration time")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, help_text="When token was used", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset Token",
                "verbose_name_plural": "Password Reset Tokens",
                "db_table": "password_reset_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "codename",
                    models.CharField(
                        help_text='Unique permission code (e.g., "tickets.add_ticket", "vehicles.change_vehicle")',
                        max_length=150,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Codename must contain only lowercase letters, numbers, dots, underscores, and hyphens",
                                regex="^[a-z0-9._-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Human-readable permission name (e.g., "Can add ticket")',
                        max_length=255,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        db_index=True,
                        help_text='Module name (e.g., "tickets", "vehicles", "hr", "reports")',
                        max_length=100,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View - Read/view access to resources"),
                            ("add", "Add - Create/add new resources"),
                            ("change", "Change - Update/modify existing resources"),
                            ("delete", "Delete - Remove resources"),
                            ("export", "Export - Export data to external formats"),
                            ("approve", "Approve - Approve/confirm actions"),
                            ("all", "All - Full access to module"),
                        ],
                        default="view",
                        help_text="Action type (view, add, change, delete, export, approve, all)",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what this permission allows",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive permissions cannot be assigned to roles",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="System permissions are predefined and cannot be modified",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this permission was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this permission was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "permissions",
                "ordering": ["module", "action", "codename"],
            },
        ),
        migrations.CreateModel(
            name="PermissionAuditLog",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("ASSIGN", "Assign"),
                            ("REVOKE", "Revoke"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "actor_id",
                    models.IntegerField(
                        blank=True,
                        help_text="User ID who performed the action",
                        null=True,
                    ),
                ),
                (
                    "actor_username",
                    models.CharField(
                        blank=True,
                        help_text="Username who performed the action",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, help_text="Previous values", null=True
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(blank=True, help_text="New values", null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Permission Audit Log",
                "verbose_name_plural": "Permission Audit Logs",
                "db_table": "permission_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PermissionCache",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cache_key",
                    models.CharField(
                        db_index=True,
                        help_text='Cache key (e.g., "user_123_permissions")',
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("permissions", models.JSONField(help_text="Cached permission data")),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this cache entry expires"),
                ),
            ],
            options={
                "verbose_name": "Permission Cache",
                "verbose_name_plural": "Permission Caches",
                "db_table": "permission_cache",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PermissionGroup",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text='Unique group code (e.g., "tickets_full_access")',
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code must contain only lowercase letters, numbers, and underscores",
                                regex="^[a-z0-9_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for permission group", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what permissions this group includes",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive groups cannot be assigned",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Group",
                "verbose_name_plural": "Permission Groups",
                "db_table": "permission_groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text='Display name of the role (e.g., "Super Administrator")',
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text='Unique identifier for the role (e.g., "super-admin", "cashier")',
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Slug must contain only lowercase letters, numbers, and hyphens",
                                regex="^[a-z0-9-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of role responsibilities",
                        null=True,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="System roles cannot be deleted and have predefined permissions",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive roles cannot be assigned to users",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Permission assignment is active (soft delete via flag)",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this permission was assigned to the role",
                    ),
                ),
                (
                    "assigned_by_id",
                    models.IntegerField(
                        blank=True,
                        help_text="User ID who assigned this permission (admin user)",
                        null=True,
                    ),
                ),
                (
                    "assigned_by_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of who assigned this permission (snapshot)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this permission was revoked from the role",
                        null=True,
                    ),
                ),
                (
                    "revoked_by_id",
                    models.IntegerField(
                        blank=True,
                        help_text="User ID who revoked this permission",
                        null=True,
                    ),
                ),
                (
                    "revoked_by_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of who revoked this permission (snapshot)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for assigning or revoking this permission",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permission",
                "verbose_name_plural": "Role Permissions",
                "db_table": "role_permissions",
                "ordering": ["role", "permission"],
            },
        ),
        migrations.CreateModel(
            name="RolePermissionAuditLog",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ASSIGN", "Assign - Permission assigned to role"),
                            ("REVOKE", "Revoke - Permission revoked from role"),
                            ("RESTORE", "Restore - Permission restored to role"),
                            (
                                "BATCH_ASSIGN",
                                "Batch Assign - Multiple permissions assigned",
                            ),
                            (
                                "BATCH_REVOKE",
                                "Batch Revoke - Multiple permissions revoked",
                            ),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                (
                    "actor_id",
                    models.IntegerField(
                        blank=True,
                        help_text="User ID who performed the action",
                        null=True,
                    ),
                ),
                (
                    "actor_username",
                    models.CharField(
                        blank=True,
                        help_text="Username who performed the action",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for the change", null=True
                    ),
                ),
                (
                    "affected_count",
                    models.IntegerField(
                        default=1,
                        help_text="Number of permissions affected (for batch operations)",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the actor", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent of the actor", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permission Audit Log",
                "verbose_name_plural": "Role Permission Audit Logs",
                "db_table": "role_permission_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionAuditLog",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login - Session created"),
                            ("LOGOUT", "Logout - Session revoked"),
                            ("TOKEN_REFRESH", "Token Refresh - New tokens generated"),
                            ("ACTIVITY", "Activity - Session activity recorded"),
                            ("SUSPICIOUS", "Suspicious - Suspicious activity detected"),
                            ("EXPIRED", "Expired - Session expired"),
                            ("REVOKED", "Revoked - Session revoked for security"),
                        ],
                        db_index=True,
                        help_text="Type of session event",
                        max_length=20,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="IP address of the event"),
                ),
                (
                    "user_agent",
                    models.TextField(help_text="User agent at time of event"),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional event details"
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Audit Log",
                "verbose_name_plural": "Session Audit Logs",
                "db_table": "session_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Role assignment is active (soft delete via flag)",
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this role was granted to the user",
                    ),
                ),
                (
                    "granted_by_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of who granted this role (snapshot)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this role was revoked from the user",
                        null=True,
                    ),
                ),
                (
                    "revoked_by_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of who revoked this role (snapshot)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for granting or revoking this role",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Role assignment expires at this time (null = never)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "db_table": "user_roles",
                "ordering": ["user", "role"],
            },
        ),
        migrations.CreateModel(
            name="UserRoleAuditLog",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ASSIGN", "Assign - Role assigned to user"),
                            ("REVOKE", "Revoke - Role revoked from user"),
                            ("RESTORE", "Restore - Role restored to user"),
                            ("BATCH_ASSIGN", "Batch Assign - Multiple roles assigned"),
                            ("BATCH_REVOKE", "Batch Revoke - Multiple roles revoked"),
                            ("EXPIRE", "Expire - Role assignment expired"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                (
                    "actor_username",
                    models.CharField(
                        blank=True,
                        help_text="Username who performed the action",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for the change", null=True
                    ),
                ),
                (
                    "affected_count",
                    models.IntegerField(
                        default=1,
                        help_text="Number of roles affected (for batch operations)",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the actor", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent of the actor", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role Audit Log",
                "verbose_name_plural": "User Role Audit Logs",
                "db_table": "user_role_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "session_token",
                    models.CharField(
                        db_index=True,
                        help_text="JWT access token for API requests",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "refresh_token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="JWT refresh token for obtaining new access tokens",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "device_info",
                    models.TextField(
                        blank=True,
                        help_text="Device information (JSON: device type, OS, browser, etc.)",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="IP address of the session"),
                ),
                (
                    "user_agent",
                    models.TextField(
                        help_text="User agent string (browser/device info)"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, help_text="When this session expires"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last activity timestamp for this session",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this session was revoked (null = active)",
                        null=True,
                    ),
                ),
                (
                    "revocation_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for revocation (logout, security, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "db_table": "user_sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
