# Generated by Django 6.0.6 on 2026-06-18 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("branches", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch where user works",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant that owns this user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_accounts",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant that owns this audit log",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="user",
            field=models.ForeignKey(
                help_text="User requesting password reset",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_reset_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent permission (for hierarchical permissions)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="accounts.permission",
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant that owns this permission",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="permissionauditlog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="permissionauditlog",
            name="permission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission_audit_logs",
                to="accounts.permission",
            ),
        ),
        migrations.AddField(
            model_name="permissionauditlog",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission_audit_logs",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="permissionauditlog",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="permissioncache",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="permissioncache",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="permissiongroup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="permissiongroup",
            name="permissions",
            field=models.ManyToManyField(
                help_text="Permissions included in this group",
                related_name="groups",
                to="accounts.permission",
            ),
        ),
        migrations.AddField(
            model_name="permissiongroup",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant that owns this permission group",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission_groups",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="permissiongroup",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant that owns this role",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="permission",
            field=models.ForeignKey(
                help_text="Permission assigned to the role",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_permissions",
                to="accounts.permission",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="role",
            field=models.ForeignKey(
                help_text="Role that has this permission",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_permissions",
                to="accounts.role",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="rolepermissionauditlog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="rolepermissionauditlog",
            name="permission",
            field=models.ForeignKey(
                blank=True,
                help_text="Permission affected (null for batch operations)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_audit_logs",
                to="accounts.permission",
            ),
        ),
        migrations.AddField(
            model_name="rolepermissionauditlog",
            name="role",
            field=models.ForeignKey(
                help_text="Role affected by this change",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission_audit_logs",
                to="accounts.role",
            ),
        ),
        migrations.AddField(
            model_name="rolepermissionauditlog",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant that owns this audit log",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_permission_audit_logs",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="rolepermissionauditlog",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="sessionauditlog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="sessionauditlog",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="sessionauditlog",
            name="user",
            field=models.ForeignKey(
                help_text="User who owns the session",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who granted this role (admin/manager)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who revoked this role",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revoked_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="role",
            field=models.ForeignKey(
                help_text="Role assigned to the user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to="accounts.role",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                help_text="User assigned to this role",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userroleauditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role_actions_performed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userroleauditlog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="userroleauditlog",
            name="role",
            field=models.ForeignKey(
                blank=True,
                help_text="Role affected (null for batch operations)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_audit_logs",
                to="accounts.role",
            ),
        ),
        migrations.AddField(
            model_name="userroleauditlog",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant that owns this audit log",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_role_audit_logs",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="userroleauditlog",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="userroleauditlog",
            name="user",
            field=models.ForeignKey(
                help_text="User affected by this change",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                help_text="User who owns this session",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sessionauditlog",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="Session related to this event",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_session_audit_logs",
                to="accounts.usersession",
            ),
        ),
        migrations.AddIndex(
            model_name="useraccount",
            index=models.Index(
                fields=["tenant", "is_active"], name="idx_user_tenant_active"
            ),
        ),
        migrations.AddIndex(
            model_name="useraccount",
            index=models.Index(
                fields=["tenant", "email"], name="idx_user_tenant_email"
            ),
        ),
        migrations.AddIndex(
            model_name="useraccount",
            index=models.Index(
                fields=["tenant", "username"], name="idx_user_tenant_username"
            ),
        ),
        migrations.AddIndex(
            model_name="useraccount",
            index=models.Index(fields=["locked_until"], name="idx_user_locked_until"),
        ),
        migrations.AddIndex(
            model_name="useraccount",
            index=models.Index(fields=["is_staff"], name="idx_user_is_staff"),
        ),
        migrations.AddConstraint(
            model_name="useraccount",
            constraint=models.UniqueConstraint(
                fields=("tenant", "username"),
                name="unique_tenant_username",
                violation_error_message="Username already exists in this tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="useraccount",
            constraint=models.UniqueConstraint(
                fields=("tenant", "email"),
                name="unique_tenant_email",
                violation_error_message="Email already exists in this tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user_id"], name="idx_audit_user"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["-created_at"], name="idx_audit_created"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["module", "action"], name="idx_audit_module"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                condition=models.Q(("object_id__isnull", False)),
                fields=["object_id"],
                name="idx_audit_object",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["request_id"], name="idx_audit_request_id"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tenant", "created_at"], name="idx_audit_tenant_created"
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(
                fields=["tenant", "module"], name="idx_permission_tenant_module"
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(
                fields=["tenant", "is_active"], name="idx_permission_tenant_active"
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["is_system"], name="idx_permission_is_system"),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(
                fields=["tenant", "action"], name="idx_permission_tenant_action"
            ),
        ),
        migrations.AddConstraint(
            model_name="permission",
            constraint=models.UniqueConstraint(
                fields=("tenant", "codename"),
                name="unique_tenant_permission_codename",
                violation_error_message="Permission codename must be unique within tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="permission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "action__in",
                        ["view", "add", "change", "delete", "export", "approve", "all"],
                    )
                ),
                name="chk_permission_action",
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["tenant", "created_at"], name="permission__tenant__005b6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(fields=["action"], name="permission__action_450007_idx"),
        ),
        migrations.AddIndex(
            model_name="permissiongroup",
            index=models.Index(
                fields=["tenant", "is_active"], name="permission__tenant__3cb0b7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="permissiongroup",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="unique_tenant_permission_group_code"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["tenant", "is_active"], name="roles_tenant__0ca5a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["is_system"], name="roles_is_syst_8ea1ed_idx"),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("tenant", "slug"), name="unique_tenant_role_slug"
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["role", "is_active"], name="idx_role_perm_role_active"
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["permission", "is_active"], name="idx_role_perm_perm_active"
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["assigned_at"], name="idx_role_perm_assigned_at"
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["role", "permission", "is_active"],
                name="idx_role_permission_composite",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "permission"),
                name="unique_role_permission",
                violation_error_message="This permission is already assigned to this role",
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermissionauditlog",
            index=models.Index(
                fields=["tenant", "created_at"], name="idx_role_perm_tenant_created"
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermissionauditlog",
            index=models.Index(
                fields=["role", "created_at"], name="idx_role_perm_at_role_created"
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermissionauditlog",
            index=models.Index(fields=["action"], name="idx_role_perm_audit_action"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["user", "is_active"], name="idx_user_role_user_active"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["role", "is_active"], name="idx_user_role_role_active"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["granted_at"], name="idx_user_role_granted_at"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["expires_at"], name="idx_user_role_expires_at"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["user", "role", "is_active"], name="idx_user_role_composite"
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                fields=("user", "role"),
                name="unique_user_role",
                violation_error_message="This role is already assigned to this user",
            ),
        ),
        migrations.AddIndex(
            model_name="userroleauditlog",
            index=models.Index(
                fields=["tenant", "created_at"], name="idx_user_role_tenant_created"
            ),
        ),
        migrations.AddIndex(
            model_name="userroleauditlog",
            index=models.Index(
                fields=["user", "created_at"], name="idx_user_role_at_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="userroleauditlog",
            index=models.Index(fields=["action"], name="idx_user_role_audit_action"),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "revoked_at"], name="idx_session_user_active"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(fields=["session_token"], name="idx_session_token"),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["refresh_token"], name="idx_session_refresh_token"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(fields=["expires_at"], name="idx_session_expires_at"),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "expires_at", "revoked_at"],
                name="idx_session_composite",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionauditlog",
            index=models.Index(
                fields=["user", "created_at"], name="idx_session_audit_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionauditlog",
            index=models.Index(
                fields=["event_type"], name="idx_session_audit_event_type"
            ),
        ),
    ]
