# Generated by Django 6.0.6 on 2026-06-18 03:12

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "key",
                    models.CharField(
                        help_text='Unique key for the feature flag (e.g., "online_payment_vnpay")',
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Key must contain only lowercase letters, numbers, and underscores",
                                regex="^[a-z0-9_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable label for the feature", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the feature",
                        null=True,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Feature flag is enabled",
                    ),
                ),
                (
                    "rollout_pct",
                    models.SmallIntegerField(
                        default=100,
                        help_text="Percentage of users to enable feature for (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "allowed_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        help_text="List of role IDs that can access this feature (null = all roles)",
                        null=True,
                    ),
                ),
                (
                    "allowed_users",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        help_text="List of user IDs that can access this feature (whitelist)",
                        null=True,
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="Feature becomes active from this date",
                        null=True,
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True,
                        help_text="Feature becomes inactive after this date",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional configuration and metadata",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this feature flag",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_flags",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
                "db_table": "feature_flags",
                "ordering": ["key"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_enabled"],
                        name="idx_feature_tenant_enabled",
                    ),
                    models.Index(
                        fields=["valid_from", "valid_to"],
                        name="idx_feature_valid_dates",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "key"),
                        name="unique_tenant_feature_key",
                        violation_error_message="Feature key must be unique within tenant",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("rollout_pct__gte", 0), ("rollout_pct__lte", 100)
                        ),
                        name="chk_rollout_pct",
                    ),
                ],
            },
        ),
    ]
