# Generated by Django 6.0.5 on 2026-06-08 11:12

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDefinition",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique system lookup identifier string token key (e.g., FINANCIAL_P_L_STATEMENT, TRIP_KPI_SUMMARY)",
                        max_length=60,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable title description banner utilized across executive dashboard reporting navigation bars",
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "REVENUE",
                                "Revenue - Financial statements, ticket sales, cash flow balances, and expense ledgers",
                            ),
                            (
                                "OPERATIONS",
                                "Operations - Fleet performance tracking, trip execution logs, and fuel allocation metrics",
                            ),
                            (
                                "HR",
                                "HR - Employee payroll registries, shift rosters, and personnel productivity auditing",
                            ),
                            (
                                "CARGO",
                                "Cargo - Logistical freight weight tracking, parcel volumes, and warehouse turnover durations",
                            ),
                            (
                                "CUSTOMERS",
                                "Customers - Passenger demographic trends, loyalty tier analytics, and churn rate matrix rows",
                            ),
                        ],
                        db_index=True,
                        help_text="The business intelligence domain vertical that this report parsing pipeline operates inside",
                        max_length=60,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Granular text detailing analytical goals, source data limitations, or interpretation guides for staff",
                        null=True,
                    ),
                ),
                (
                    "query_config",
                    models.JSONField(
                        default=dict,
                        help_text="JSON metadata mapping analytical extraction rules (filters, aggregation dimensions, selected KPI metrics)",
                    ),
                ),
                (
                    "chart_config",
                    models.JSONField(
                        default=dict,
                        help_text="JSON metadata mapping data rendering instructions (visualization type e.g. line/bar/pie, axis bindings, UI themes)",
                    ),
                ),
                (
                    "is_builtin",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Flag marking core hardcoded system reports. Protects critical core records from casual user deletions.",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Determines visibility bounds. When TRUE, other global operators within this node can inspect layout metrics.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now,
                        help_text="Timezone-aware record logging anchor tracking exactly when this report definition row was initialized",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp tracking exactly when parameter attributes inside this analytics structure node mutated",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specialized user account profile or BI analyst who constructed this dynamic configuration layout",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reports",
                        to="accounts.useraccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant corporate owner holding legal data sovereignty over this analytics report definition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_definitions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Definition Blueprint",
                "verbose_name_plural": "Report Definition Blueprints",
                "db_table": "report_definitions",
                "ordering": ["tenant_id", "-is_builtin", "category", "code"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Short descriptive title identifying this background automated mailing task schedule configuration",
                        max_length=100,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            (
                                "DAILY",
                                "Daily - Dispatches compiled blueprints once every calendar day loop",
                            ),
                            (
                                "WEEKLY",
                                "Weekly - Executes summary analytical matrices once every seven calendar days",
                            ),
                            (
                                "MONTHLY",
                                "Monthly - Fires off deep period balance sheet summaries at month-end close dates",
                            ),
                        ],
                        db_index=True,
                        help_text="The high-level macro cyclic category block governing transmission timing patterns",
                        max_length=20,
                    ),
                ),
                (
                    "cron_expr",
                    models.CharField(
                        blank=True,
                        help_text='Standard five-field Unix crontab string syntax expression for custom precision execution mapping (e.g., "30 7 * * 1-5")',
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        default=list,
                        help_text='JSONB array containing direct communication delivery routing targets. Structure layout: [{"type": "email"|"user", "value": "..."}]',
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            (
                                "PDF",
                                "PDF - Portable Document Format layout configured for print-ready layout reviews",
                            ),
                            (
                                "EXCEL",
                                "Excel - Structured digital spreadsheet workbook optimized for manual data audits",
                            ),
                            (
                                "CSV",
                                "CSV - Raw comma-separated values document tailored for external analytical processing pipelines",
                            ),
                        ],
                        default="PDF",
                        help_text="The physical target electronic extension file format structure built during task rendering executions",
                        max_length=10,
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware calendar timestamp documenting the last moment this automation task ran successfully",
                        null=True,
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timezone-aware timestamp marking the immediate future target milestone when background workers should run this row",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Master administrative toggle switch. Turning this off flags the worker pool daemon to ignore scheduling executions for this row.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now,
                        help_text="Timezone-aware log record tracking exactly when this schedule record entry was registered inside the database",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        help_text="The dynamic database analytics report definition blueprint model acting as the extraction engine for this job",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="reports.reportdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Automated Report Schedule",
                "verbose_name_plural": "Automated Report Schedules",
                "db_table": "scheduled_reports",
                "ordering": ["-is_active", "next_run_at", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="reportdefinition",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_tenant_report_definition_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "category__in",
                        ["REVENUE", "OPERATIONS", "HR", "CARGO", "CUSTOMERS"],
                    )
                ),
                name="chk_report_definition_category_enum",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledreport",
            constraint=models.CheckConstraint(
                condition=models.Q(("frequency__in", ["DAILY", "WEEKLY", "MONTHLY"])),
                name="chk_scheduled_report_frequency_enum",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledreport",
            constraint=models.CheckConstraint(
                condition=models.Q(("format__in", ["PDF", "EXCEL", "CSV"])),
                name="chk_scheduled_report_format_enum",
            ),
        ),
    ]
