# Generated by Django 6.0.5 on 2026-06-05 16:19

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("customers_tickets", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="The alphanumeric string coupon key typed by passenger consumers at checkout panels (e.g., SUMMER26)",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Public human-readable campaign label text displayed across booking screens (e.g., Grand Opening Discount)",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Internal structural scope explanations or visible marketing terms and conditions rules text",
                        null=True,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            (
                                "PERCENT",
                                "Percentage - Scaled mathematical deduction bounded by max limits",
                            ),
                            (
                                "FIXED_AMOUNT",
                                "Fixed Amount - Absolute invariant commercial currency value deduction",
                            ),
                            (
                                "FREE_SEAT",
                                "Free Seat - Total asset valuation waiver for applied line units",
                            ),
                        ],
                        db_index=True,
                        help_text="The algorithmic strategy chosen to compute transaction price deductions",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The active calculation metric magnitude multiplier. Represents percentages (e.g., 15.50) or absolute currencies (e.g., 50000.00)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum aggregate shopping cart invoice threshold required to trigger this calculation layout engine",
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The structural ceiling safety limit preventing percentage-based deductions from draining excessive campaign funds",
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "usage_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Total cumulative times this code can clear checkpoints system-wide across all consumers prior to exhaustion",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "usage_limit_per_user",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum allocation cycles a single unique client identity identity token can execute this specific code block",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0,
                        help_text="Live database increment index logging exactly how many times checkout checkouts successfully consumed this coupon line",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "applicable_routes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        help_text="List arrays storing target Route database keys allowed to consume this coupon line. Empty arrays match ALL paths.",
                        null=True,
                    ),
                ),
                (
                    "applicable_seat_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        help_text="List arrays storing distinct cabin classes eligible to request reductions (e.g., [VIP_SLEEPER, STANDARD_SEAT])",
                        null=True,
                    ),
                ),
                (
                    "applicable_channels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        help_text="List arrays restricting coupon activation to discrete sale gateways (e.g., [MOBILE_APP, B2B_AGENT, COUNTER_DESK])",
                        null=True,
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        help_text="Timezone-aware activation timeline node marking exactly when this coupon rule goes live online"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware expiration date node marking exactly when this coupon ruleset automatically loses legal status",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Master administrative toggle switch. Setting this false instantly blocks all checkout applications regardless of chronology rules",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now,
                        help_text="System record logging anchor tracking exactly when this rule layout row entered the central database",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp tracking when parameters inside this promotional campaign node were last modified",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific internal marketing manager or administrator account who configured this coupon schema",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_promotions",
                        to="accounts.useraccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant owner corporate node managing this isolated pricing coupon campaign leaf",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotional Coupon",
                "verbose_name_plural": "Promotional Coupons",
                "db_table": "promotions",
                "ordering": ["-created_at", "code"],
            },
        ),
        migrations.CreateModel(
            name="PromotionUsage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "discount_applied",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The exact absolute cash currency credit value subtracted from the gross order ticket total",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now,
                        help_text="Timezone-aware timestamp logging exactly when this voucher link cleared checkout pipelines",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        help_text="The target passenger fare booking order invoice where this discount credit was applied",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotion_usages",
                        to="customers_tickets.ticketbooking",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="The unique verified customer profile account who claimed and executed this code",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coupon_usages",
                        to="customers_tickets.customer",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        help_text="The parent promotion coupon master rule instance consumed in this transaction context",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usages",
                        to="promotions_loyalty.promotion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion Usage Log",
                "verbose_name_plural": "Promotion Usage Logs",
                "db_table": "promotion_usages",
                "ordering": ["-used_at"],
            },
        ),
        migrations.CreateModel(
            name="AfterSales",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="The unique system text key code used to classify this retention policy rule (e.g., RETURN_USER_BONUS)",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Public or internal campaign title descriptive name text displayed in administrative panels",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed descriptions capturing operational parameters, policy scopes, or audit notes",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (
                                "VOUCHER",
                                "Voucher - High-fidelity electronic balance debit card generation",
                            ),
                            (
                                "LOYALTY_POINTS",
                                "Loyalty Points - Automated quantitative membership wallet point injections",
                            ),
                            (
                                "GIFT",
                                "Gift - Physical merchandise line item inventory claiming authorization",
                            ),
                            (
                                "DISCOUNT_CODE",
                                "Discount Code - Dynamic customized checkout promotional coupon generation",
                            ),
                        ],
                        db_index=True,
                        help_text="The primary rewarding strategy type framework deployed upon successful qualification check clears",
                        max_length=30,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The raw magnitude scale tracking reward values. Maps to cash weight balances, absolute point counts, or percentages.",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict,
                        help_text='Schemaless validation rule matrices mapping criteria fields (e.g., {"target_route_id": 5, "min_spend": 200000})',
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Master state switch engine. Setting this False safely deactivates the automatic rule logic processing queues instantly",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now,
                        help_text="System record logging anchor tracking exactly when this rule layout row entered the main database",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp tracking exactly when parameter attributes inside this after-sales configuration node mutated",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The authorized system administrator or marketing strategist user account who compiled this reward matrix",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_after_sales",
                        to="accounts.useraccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant corporate owner holding legal data sovereignty over this CRM retention campaign node",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="after_sales_policies",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "After-Sales Policy",
                "verbose_name_plural": "After-Sales Policies",
                "db_table": "after_sales",
                "ordering": ["-created_at", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "code"), name="uq_tenant_after_sales_code"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "type__in",
                                ["VOUCHER", "LOYALTY_POINTS", "GIFT", "DISCOUNT_CODE"],
                            )
                        ),
                        name="chk_after_sales_type_enum",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("value__gte", 0), ("value__isnull", True), _connector="OR"
                        ),
                        name="chk_after_sales_value_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyTransaction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (
                                "EARN",
                                "Earn - Points accumulated from booking purchases or marketing check-ins",
                            ),
                            (
                                "REDEEM",
                                "Redeem - Points liquidated as commercial cash credits during order checkouts",
                            ),
                            (
                                "EXPIRE",
                                "Expire - Unused points passing past chronological validity deadlines",
                            ),
                            (
                                "ADJUST",
                                "Adjust - Administrative balance adjustments handled by support staff agents",
                            ),
                        ],
                        db_index=True,
                        help_text="The dynamic action vector classification tracking the direction of this point mutation entry",
                        max_length=20,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="The absolute value magnitude of points shifted in this event. Can hold negative values for deductions."
                    ),
                ),
                (
                    "balance",
                    models.IntegerField(
                        help_text="The historical running snapshot balance total remaining inside the customer wallet immediately post-transaction"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed textual ledger notes specifying why this change triggered (e.g., Earned from Trip Hanoi-Haiphong)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now,
                        help_text="Timezone-aware timestamp logging exactly when this point entry row committed into storage blocks",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific revenue order booking ticket that triggered this points event. Holds NULL for adjustments or expiries.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyalty_transactions",
                        to="customers_tickets.ticketbooking",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="The parent client identity account profile who owns this points transaction snapshot",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_transactions",
                        to="customers_tickets.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyalty Points Transaction",
                "verbose_name_plural": "Loyalty Points Transactions",
                "db_table": "loyalty_transactions",
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("type__in", ["EARN", "REDEEM", "EXPIRE", "ADJUST"])
                        ),
                        name="chk_loyalty_transaction_type_rules",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("balance__gte", 0)),
                        name="chk_loyalty_wallet_balance_positive",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_tenant_promotion_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_type__in", ["PERCENT", "FIXED_AMOUNT", "FREE_SEAT"])
                ),
                name="chk_promotion_discount_type_enum",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_value__gte", 0), ("usage_count__gte", 0)),
                name="chk_promotion_metrics_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__gt", models.F("valid_from")),
                    ("valid_to__isnull", True),
                    _connector="OR",
                ),
                name="chk_promotion_timeline_validity",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotionusage",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_applied__gte", 0)),
                name="chk_promotion_usage_discount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotionusage",
            constraint=models.UniqueConstraint(
                fields=("promotion", "booking"),
                name="uq_promotion_per_booking_instance",
            ),
        ),
    ]
