# Generated by Django 6.0.5 on 2026-06-09 08:34

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("branches", "0001_initial"),
        ("hr", "0001_initial"),
        ("tenants", "0001_initial"),
        ("trips", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="The specialized uppercase system billing key token (e.g., FUEL_DIESEL, OFFICE_RENT)",
                        max_length=30,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable balance sheet title label used across corporate ledger accounting dashboards",
                        max_length=100,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now,
                        help_text="Timezone-aware record logging anchor tracking exactly when this financial category row was initialized",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pointer referencing the higher-level master accounting classification group. Sits NULL for root categories.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategories",
                        to="financials.expensecategory",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant corporate corporate node holding legal data sovereignty over this account code structure",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_categories",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corporate Expense Category",
                "verbose_name_plural": "Corporate Expense Categories",
                "db_table": "expense_categories",
                "ordering": ["tenant", "parent_id", "code"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Short human-readable summary name identifying this expense (e.g., 50L Oil Topup Plate 30K-9999)",
                        max_length=255,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The exact mathematical total cash volume spent or requested for this specific line item voucher",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(
                        db_index=True,
                        help_text="The real-world business calendar date when the money was spent or when the physical invoice receipt was printed",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Granular descriptive annotations or breakdown justifications clarifying specific line parameters",
                        null=True,
                    ),
                ),
                (
                    "attachment",
                    models.CharField(
                        blank=True,
                        help_text="Cloud storage object URL or server location path pointing to scanned PDF invoices or picture receipts",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "PENDING",
                                "Pending - Newly stashed entry, awaiting financial auditor review clearance",
                            ),
                            (
                                "APPROVED",
                                "Approved - Budget verified and locked, awaiting physical bank or cash box release",
                            ),
                            (
                                "REJECTED",
                                "Rejected - Auditing denied by management, execution pipeline aborted",
                            ),
                            (
                                "PAID",
                                "Paid - Cash out successfully completed, bank voucher finalized and closed",
                            ),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="The structural processing stage tracking this cost through auditing and layout payment lifecycles",
                        max_length=20,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware timestamp logging exactly when an authorized executive approved or rejected this file",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now,
                        help_text="System record logging anchor tracking exactly when this entry row was stashed in the main DB",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp tracking exactly when parameter attributes inside this financial voucher node mutated",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The chief accountant or regional financial executive approving or rejecting this budget payout request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to="accounts.useraccount",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="The corporate physical branch office or office station responsible for incurring this liability",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="branches.branch",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff member or operational driver to whom this expenditure cash allocation is credited",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="hr.employee",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The internal operator user account or accounting assistant filing this invoice data row into storage",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_expenses",
                        to="accounts.useraccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant corporate node owning and financing this commercial outlay row",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        help_text="The operational route trip execution context where this cost was generated (e.g., bridge toll fees)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="trips.trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        help_text="The target fleet vehicle profile consuming this cash resource (e.g., fuel, tires, repairs)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="vehicles.vehicle",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The specialized financial account category code grouping this type of cost outlay",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="financials.expensecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corporate Expense Voucher",
                "verbose_name_plural": "Corporate Expense Vouchers",
                "db_table": "expenses",
                "ordering": ["-expense_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FuelAllocation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "liters",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The volume of fuel pumped, measured precisely in liters",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "price_per_liter",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The single unit market price weight per fuel liter at the timestamp of allocation (e.g., VND/Liter)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The aggregate financial liability cash weight (liters multiplied by price_per_liter)",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "station_name",
                    models.CharField(
                        blank=True,
                        help_text="The physical commercial brand name or location metadata text of the gas pump station (e.g., PV OIL Branch 2)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "odometer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The absolute physical counter dashboard mileage meter reading snapshot at refueling checkpoint",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Granular operational explanations or unexpected incident logging data lines",
                        null=True,
                    ),
                ),
                (
                    "allocated_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now,
                        help_text="Timezone-aware calendar timestamp tracking when the physical fuel was dispensed into the tank",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now,
                        help_text="System log row registration initialization milestone timestamp",
                    ),
                ),
                (
                    "allocated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The dispatcher clerk or internal back-office user logging or signing off this fuel ticket voucher",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorized_fuel_allocations",
                        to="accounts.useraccount",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        help_text="The professional driver operational employee operating the vehicle at the timestamp of refueling",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuel_allocations",
                        to="hr.employee",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific operational route journey execution segment where this fuel consumption is assigned",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuel_allocations",
                        to="trips.trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        help_text="The target fleet vehicle profile node receiving the physical fuel volume injection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_allocations",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fuel Allocation Voucher",
                "verbose_name_plural": "Fuel Allocation Vouchers",
                "db_table": "fuel_allocations",
                "ordering": ["vehicle", "-allocated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="expensecategory",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_tenant_expense_category_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["PENDING", "APPROVED", "REJECTED", "PAID"])
                ),
                name="chk_expense_status_rules",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="chk_expense_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="fuelallocation",
            index=models.Index(
                fields=["vehicle", "-allocated_at"], name="idx_fuel_vehicle"
            ),
        ),
        migrations.AddConstraint(
            model_name="fuelallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("liters__gt", 0), ("price_per_liter__gt", 0), ("total_cost__gt", 0)
                ),
                name="chk_fuel_metrics_strictly_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="fuelallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("odometer__gte", 0), ("odometer__isnull", True), _connector="OR"
                ),
                name="chk_fuel_odometer_positive",
            ),
        ),
    ]
