# Generated by Django 6.0.5 on 2026-06-02 13:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "slug",
                    models.CharField(
                        help_text='URL-friendly identifier (e.g., "vip-customer")',
                        max_length=80,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Slug must contain only lowercase letters, numbers, and hyphens",
                                regex="^[a-z0-9\\-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Human-readable label (e.g., "VIP Customer")',
                        max_length=100,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6B7280",
                        help_text="Hex color code for visual identification",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Color must be a valid hex color (e.g., #6B7280)",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this tag was created",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this tag",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "tags",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="EntityTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text='Type of entity being tagged (e.g., "bookings", "vehicles")',
                        max_length=60,
                    ),
                ),
                (
                    "entity_id",
                    models.BigIntegerField(
                        db_index=True, help_text="ID of entity being tagged"
                    ),
                ),
                (
                    "tagged_by_username",
                    models.CharField(
                        blank=True,
                        help_text="Username snapshot at time of tagging",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "tagged_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this tag was applied",
                    ),
                ),
                (
                    "tagged_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who applied this tag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entity_tags_created",
                        to="accounts.useraccount",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="Tag applied to entity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_tags",
                        to="tags.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Tag",
                "verbose_name_plural": "Entity Tags",
                "db_table": "entity_tags",
                "ordering": ["-tagged_at"],
            },
        ),
        migrations.CreateModel(
            name="TaggedItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of entity being tagged",
                        max_length=60,
                    ),
                ),
                (
                    "entity_id",
                    models.IntegerField(
                        db_index=True, help_text="ID of entity being tagged"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this tag was applied",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="Tag applied to entity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="tags.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tagged Item",
                "verbose_name_plural": "Tagged Items",
                "db_table": "tagged_items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["tenant"], name="idx_tag_tenant"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["slug"], name="idx_tag_slug"),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("tenant", "slug"),
                name="unique_tenant_tag_slug",
                violation_error_message="Tag slug must be unique within tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="entitytag",
            index=models.Index(
                fields=["entity_type", "entity_id"], name="idx_entity_tags_lookup"
            ),
        ),
        migrations.AddIndex(
            model_name="entitytag",
            index=models.Index(
                fields=["tag", "entity_type"], name="idx_entity_tags_tag_type"
            ),
        ),
        migrations.AddIndex(
            model_name="entitytag",
            index=models.Index(
                fields=["tagged_by", "tagged_at"], name="idx_entity_tags_user_time"
            ),
        ),
        migrations.AddConstraint(
            model_name="entitytag",
            constraint=models.UniqueConstraint(
                fields=("tag", "entity_type", "entity_id"),
                name="unique_entity_tag",
                violation_error_message="Entity already has this tag",
            ),
        ),
        migrations.AddIndex(
            model_name="taggeditem",
            index=models.Index(
                fields=["entity_type", "entity_id"], name="idx_tagged_entity"
            ),
        ),
        migrations.AddIndex(
            model_name="taggeditem",
            index=models.Index(
                fields=["tag", "entity_type"], name="idx_tagged_tag_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="taggeditem",
            constraint=models.UniqueConstraint(
                fields=("tag", "entity_type", "entity_id"),
                name="unique_tag_entity",
                violation_error_message="Entity already has this tag",
            ),
        ),
    ]
