# Generated by Django 6.0.5 on 2026-06-01 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('branches', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the task list', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this task list was created')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this task list belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_lists', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this task list', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_lists_created', to='accounts.useraccount')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this task list', on_delete=django.db.models.deletion.CASCADE, related_name='task_lists', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Task List',
                'verbose_name_plural': 'Task Lists',
                'db_table': 'task_lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Task title', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Detailed task description', null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low - Can be done anytime'), ('MEDIUM', 'Medium - Regular priority'), ('HIGH', 'High - Important task'), ('URGENT', 'Urgent - Must be done immediately')], db_index=True, default='MEDIUM', help_text='Task priority', max_length=10)),
                ('status', models.CharField(choices=[('TODO', 'To Do - Not started'), ('IN_PROGRESS', 'In Progress - Currently being worked on'), ('REVIEW', 'Review - Waiting for review'), ('DONE', 'Done - Task completed'), ('CANCELLED', 'Cancelled - Task cancelled')], db_index=True, default='TODO', help_text='Task status', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, db_index=True, help_text='Due date for task', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When task was completed', null=True)),
                ('entity_type', models.CharField(blank=True, db_index=True, help_text='Type of entity this task is linked to', max_length=60, null=True)),
                ('entity_id', models.BigIntegerField(blank=True, db_index=True, help_text='ID of entity this task is linked to', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When task was last updated')),
                ('assignee', models.ForeignKey(blank=True, help_text='User this task is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='accounts.useraccount')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to='accounts.useraccount')),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tenants.tenant')),
                ('list', models.ForeignKey(blank=True, help_text='Task list this task belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.tasklist')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'ordering': ['-priority', 'due_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tasklist',
            index=models.Index(fields=['tenant'], name='idx_task_list_tenant'),
        ),
        migrations.AddIndex(
            model_name='tasklist',
            index=models.Index(fields=['branch'], name='idx_task_list_branch'),
        ),
        migrations.AddIndex(
            model_name='tasklist',
            index=models.Index(fields=['created_by'], name='idx_task_list_creator'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee_id'], name='idx_tasks_assignee'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['entity_type', 'entity_id'], name='idx_tasks_entity'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(condition=models.Q(('status__in', ['TODO', 'IN_PROGRESS', 'REVIEW'])), fields=['status'], name='idx_tasks_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date', 'status'], name='idx_tasks_due_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'status'], name='idx_tasks_tenant_status'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['LOW', 'MEDIUM', 'HIGH', 'URGENT'])), name='chk_task_priority', violation_error_message='Invalid priority value'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['TODO', 'IN_PROGRESS', 'REVIEW', 'DONE', 'CANCELLED'])), name='chk_task_status', violation_error_message='Invalid status value'),
        ),
    ]
