# Generated by Django 6.0.6 on 2026-07-09 03:50

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleCategory",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique category code per tenant (e.g., STD-45, VIP-22)",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code must contain only uppercase letters, numbers, hyphens, and underscores",
                                regex="^[A-Z0-9\\-_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the category", max_length=100
                    ),
                ),
                (
                    "seat_count",
                    models.PositiveSmallIntegerField(
                        help_text="Total number of passenger seats/berths available"
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("BUS", "Bus - Standard Seating Bus"),
                            ("SLEEPER_BUS", "Sleeper Bus - Cabin/Bed Bus"),
                            ("LIMOUSINE", "Limousine - Luxury Vehicle"),
                            ("MINIBUS", "Minibus - Small Capacity Van"),
                            ("OTHER", "Other - Custom Vehicle Type"),
                        ],
                        db_index=True,
                        help_text="Classification type of the vehicle",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the category and its configuration",
                        null=True,
                    ),
                ),
                (
                    "amenities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="List of available features (e.g., wifi, ac, usb, tv)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this category is active and can be assigned to new vehicles",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant owner of this vehicle category",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_categories",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Category",
                "verbose_name_plural": "Vehicle Categories",
                "db_table": "vehicle_categories",
                "ordering": ["tenant", "vehicle_type", "code"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "plate_number",
                    models.CharField(
                        help_text="Unique official vehicle license plate number (e.g., 29A-123.45)",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Plate number format is invalid",
                                regex="^[A-Z0-9\\-.\\s]+$",
                            )
                        ],
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        blank=True,
                        help_text="Vehicle Identification Number (Chassis number)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "manufacture_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Year of manufacture/production",
                        null=True,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="Manufacturer brand (e.g., Hyundai, Thaco, Ford)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="Specific manufacturing model name",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Exterior color description",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available - Ready for service"),
                            ("IN_TRIP", "In Trip - Currently operational on a route"),
                            ("MAINTENANCE", "Maintenance - In garage or workshop"),
                            ("INACTIVE", "Inactive - Temporarily decommissioned"),
                            ("DISPOSED", "Disposed - Permanently out of fleet"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        help_text="Current technical or operation lifecycle state",
                        max_length=30,
                    ),
                ),
                (
                    "odometer_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total cumulative tracked mileage in kilometers",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "registration_expiry",
                    models.DateField(
                        blank=True,
                        help_text="Expiry date of the vehicle official legal registration",
                        null=True,
                    ),
                ),
                (
                    "insurance_expiry",
                    models.DateField(
                        blank=True,
                        help_text="Expiry date of the vehicle civil liability/hull insurance policy",
                        null=True,
                    ),
                ),
                (
                    "inspection_expiry",
                    models.DateField(
                        blank=True,
                        help_text="Expiry date of the vehicle technical safety inspection certificate",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal operational logs, repair flags, or general annotations",
                        null=True,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current managing or home branch location",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicles",
                        to="branches.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant owner of this vehicle",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Vehicle specification category profile",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="vehicles",
                        to="vehicles.vehiclecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "db_table": "vehicles",
                "ordering": ["tenant", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SeatMap",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive title of the layout configuration template (e.g., Standard 2+2 Layout)",
                        max_length=100,
                    ),
                ),
                (
                    "total_seats",
                    models.PositiveSmallIntegerField(
                        help_text="Declared number of total sellable seats configured inside this map blueprint"
                    ),
                ),
                (
                    "layout_config",
                    models.JSONField(
                        default=dict,
                        help_text="Complex data object matrix capturing row, col, type, floor and specific coordinate structures",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Vehicle category profile this schematic blueprint applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_maps",
                        to="vehicles.vehiclecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seat Map",
                "verbose_name_plural": "Seat Maps",
                "db_table": "seat_maps",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="VehicleMaintenance",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled - Preventive maintenance"),
                            ("EMERGENCY", "Emergency - Unplanned breakthrough repairs"),
                            ("INSPECTION", "Inspection - Diagnostic safety check"),
                            ("CLEANING", "Cleaning - Commercial valeting service"),
                        ],
                        db_index=True,
                        help_text="Classification categories distinguishing service context",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed logs explaining mechanical faults, parts swapped, or work scope"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total cumulative monetary value billed for parts and labor",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        help_text="Name of the external garage, workshop, or third-party service provider",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "odometer_in",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Odometer reading when the vehicle entered the workshop",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "odometer_out",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Odometer reading when the vehicle left the workshop",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateField(
                        blank=True,
                        help_text="Target date on which this maintenance task is planned to occur",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateField(
                        blank=True,
                        help_text="Official date when the job card was signed off as completed",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending - Awaiting slot or approval"),
                            ("IN_PROGRESS", "In Progress - Vehicle in workshop"),
                            ("DONE", "Done - Maintenance successfully completed"),
                            ("CANCELLED", "Cancelled - Operation aborted"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Operational stage representing current job progression state",
                        max_length=20,
                    ),
                ),
                (
                    "next_due_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Predicted mileage target threshold when the asset must return for the next cycle",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "next_due_date",
                    models.DateField(
                        blank=True,
                        help_text="Calendar target date dead-line when the asset must return for the next cycle",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff member or technician responsible for managing this operation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_maintenances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        help_text="The specific vehicle asset undergoing maintenance",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenances",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Maintenance",
                "verbose_name_plural": "Vehicle Maintenances",
                "db_table": "vehicle_maintenance",
                "ordering": ["-scheduled_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "seat_code",
                    models.CharField(
                        help_text="Unique identifier code displayed to customer (e.g., A1, 12B, VIP-01)",
                        max_length=10,
                    ),
                ),
                (
                    "seat_type",
                    models.CharField(
                        choices=[
                            ("SEAT", "Seat - Standard sitting chair"),
                            ("BED", "Bed - Sleeper berth cabin"),
                            ("VIP", "VIP - Ultra luxury private space"),
                            ("PREMIUM", "Premium - Enhanced comfort seating"),
                        ],
                        db_index=True,
                        default="SEAT",
                        help_text="Classification type representing comfort spec and pricing tier",
                        max_length=30,
                    ),
                ),
                (
                    "deck",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Deck/Floor layer identifier (e.g., 1 for Lower Deck, 2 for Upper Deck)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "row_num",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Matrix grid logical row sequence coordinate index number",
                        null=True,
                    ),
                ),
                (
                    "col_num",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Matrix grid logical column sequence coordinate index number",
                        null=True,
                    ),
                ),
                (
                    "position_x",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Absolute or relative graphic coordinate factor mapping onto X horizontal axis",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "position_y",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Absolute or relative graphic coordinate factor mapping onto Y vertical axis",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this seat template unit is structurally ready for commercial usage",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "seat_map",
                    models.ForeignKey(
                        help_text="The blueprint seat map configuration template this unit belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="vehicles.seatmap",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seat",
                "verbose_name_plural": "Seats",
                "db_table": "seats",
                "ordering": ["seat_map", "deck", "row_num", "col_num", "seat_code"],
                "indexes": [
                    models.Index(
                        fields=["seat_map", "deck", "is_available"],
                        name="idx_seat_map_deck_operational",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("seat_map", "seat_code"), name="unique_seat_map_code"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("seat_type__in", ["SEAT", "BED", "VIP", "PREMIUM"])
                        ),
                        name="chk_seat_type",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="vehiclecategory",
            index=models.Index(
                fields=["tenant", "is_active"], name="idx_veh_cat_tenant_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="vehiclecategory",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="unique_tenant_vehicle_category_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="vehiclecategory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "vehicle_type__in",
                        ["BUS", "SLEEPER_BUS", "LIMOUSINE", "MINIBUS", "OTHER"],
                    )
                ),
                name="chk_vehicle_type",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["branch", "status"], name="idx_vehicle_branch_status"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["inspection_expiry", "insurance_expiry"],
                name="idx_vehicle_compliance_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["AVAILABLE", "IN_TRIP", "MAINTENANCE", "INACTIVE", "DISPOSED"],
                    )
                ),
                name="chk_vehicle_status",
            ),
        ),
        migrations.AddIndex(
            model_name="seatmap",
            index=models.Index(fields=["category", "name"], name="idx_seat_map_lookup"),
        ),
        migrations.AddIndex(
            model_name="vehiclemaintenance",
            index=models.Index(
                fields=["vehicle", "status"], name="idx_maint_vehicle_status"
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclemaintenance",
            index=models.Index(
                fields=["scheduled_at", "completed_at"],
                name="idx_maint_timeline_metrics",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehiclemaintenance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("type__in", ["SCHEDULED", "EMERGENCY", "INSPECTION", "CLEANING"])
                ),
                name="chk_maintenance_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehiclemaintenance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["PENDING", "IN_PROGRESS", "DONE", "CANCELLED"])
                ),
                name="chk_maintenance_status",
            ),
        ),
    ]
