# Generated by Django 6.0.5 on 2026-06-02 13:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuAuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create - Menu item created"),
                            ("UPDATE", "Update - Menu item modified"),
                            ("DELETE", "Delete - Menu item deleted"),
                            ("REORDER", "Reorder - Menu items reordered"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_actions_performed",
                        to="accounts.useraccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_audit_logs",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Audit Log",
                "verbose_name_plural": "Menu Audit Logs",
                "db_table": "menu_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MenuGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text='Unique code for the menu group (e.g., "operations", "hr")',
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code must contain only lowercase letters, numbers, and underscores",
                                regex="^[a-z0-9_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Display label for the menu group (e.g., "Vận hành xe")',
                        max_length=100,
                    ),
                ),
                (
                    "icon",
                    models.TextField(
                        blank=True,
                        help_text='SVG path string or icon name (e.g., "mdi-truck", "<svg>...</svg>")',
                        null=True,
                    ),
                ),
                (
                    "sort_order",
                    models.SmallIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Display order (lower values appear first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Menu group is active and visible",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this menu group was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this menu group was last updated"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this menu group",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_groups",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Group",
                "verbose_name_plural": "Menu Groups",
                "db_table": "menu_groups",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the menu item",
                        max_length=80,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code must contain only lowercase letters, numbers, and underscores",
                                regex="^[a-z0-9_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label for the menu item", max_length=150
                    ),
                ),
                (
                    "url_name",
                    models.CharField(
                        blank=True,
                        help_text='Django URL name or route name (e.g., "tickets:list")',
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "url_path",
                    models.CharField(
                        blank=True,
                        help_text='Static URL path fallback (e.g., "/tickets/list")',
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "icon",
                    models.TextField(
                        blank=True,
                        help_text='SVG path string or icon name (e.g., "mdi-list")',
                        null=True,
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(
                        blank=True,
                        help_text='Badge text (e.g., "NEW", "BETA", "5" for notifications)',
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "badge_color",
                    models.CharField(
                        default="#EF4444",
                        help_text="Badge color in hex format (default: red #EF4444)",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Badge color must be a valid hex color (e.g., #EF4444)",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "permission_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Required permission code to view this item",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "sort_order",
                    models.SmallIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Display order (lower values appear first)",
                    ),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=False, help_text="Open URL in new tab/window"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Menu item is active and visible",
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Item is hidden from menu but route still works",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this menu item was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this menu item was last updated"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Menu group this item belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_items",
                        to="menus.menugroup",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent menu item (for nested menus)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="menus.menuitem",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this menu item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item",
                "verbose_name_plural": "Menu Items",
                "db_table": "menu_items",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="MenuItemRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        help_text="Menu item assigned to this role",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="menus.menuitem",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="Role that can access this menu item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_item_assignments",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item Role",
                "verbose_name_plural": "Menu Item Roles",
                "db_table": "menu_item_roles",
            },
        ),
        migrations.CreateModel(
            name="MenuItemRoleAuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ASSIGN", "Assign - Role assigned to menu item"),
                            ("REVOKE", "Revoke - Role revoked from menu item"),
                            ("BATCH_ASSIGN", "Batch Assign - Multiple roles assigned"),
                            ("BATCH_REVOKE", "Batch Revoke - Multiple roles revoked"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                (
                    "actor_username",
                    models.CharField(
                        blank=True,
                        help_text="Username who performed the action",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "affected_count",
                    models.IntegerField(
                        default=1,
                        help_text="Number of roles affected (for batch operations)",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for the change", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_item_role_actions_performed",
                        to="accounts.useraccount",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        help_text="Menu item affected by this change",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_audit_logs",
                        to="menus.menuitem",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Role affected (null for batch operations)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_item_audit_logs",
                        to="accounts.role",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this audit log",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_item_role_audit_logs",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item Role Audit Log",
                "verbose_name_plural": "Menu Item Role Audit Logs",
                "db_table": "menu_item_role_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="menugroup",
            index=models.Index(
                fields=["tenant", "is_active"], name="idx_menu_group_tenant_active"
            ),
        ),
        migrations.AddIndex(
            model_name="menugroup",
            index=models.Index(
                fields=["tenant", "sort_order"], name="idx_menu_group_tenant_sort"
            ),
        ),
        migrations.AddConstraint(
            model_name="menugroup",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"),
                name="unique_tenant_menu_group_code",
                violation_error_message="Menu group code must be unique within tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["tenant", "is_active"], name="idx_menu_item_tenant_active"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["group", "is_active"], name="idx_menu_item_group_active"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["parent", "sort_order"], name="idx_menu_item_parent_sort"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["permission_code"], name="idx_menu_item_permission"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(fields=["is_hidden"], name="idx_menu_item_hidden"),
        ),
        migrations.AddConstraint(
            model_name="menuitem",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"),
                name="unique_tenant_menu_item_code",
                violation_error_message="Menu item code must be unique within tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="menuitemrole",
            index=models.Index(fields=["menu_item"], name="idx_menu_item_role_item"),
        ),
        migrations.AddIndex(
            model_name="menuitemrole",
            index=models.Index(fields=["role"], name="idx_menu_item_role_role"),
        ),
        migrations.AddConstraint(
            model_name="menuitemrole",
            constraint=models.UniqueConstraint(
                fields=("menu_item", "role"),
                name="unique_menu_item_role",
                violation_error_message="This role is already assigned to this menu item",
            ),
        ),
        migrations.AddIndex(
            model_name="menuitemroleauditlog",
            index=models.Index(
                fields=["tenant", "created_at"], name="idx_menui_role_tenant_created"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitemroleauditlog",
            index=models.Index(
                fields=["menu_item", "created_at"], name="idx_menu_item_role_created"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitemroleauditlog",
            index=models.Index(fields=["action"], name="idx_menu_item_role_at_action"),
        ),
    ]
