# Generated by Django 6.0.6 on 2026-06-18 03:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="Unique identifier for this file",
                        unique=True,
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        help_text="Original filename as uploaded", max_length=500
                    ),
                ),
                (
                    "stored_name",
                    models.CharField(
                        help_text="Sanitized filename for storage", max_length=500
                    ),
                ),
                (
                    "storage",
                    models.CharField(
                        choices=[
                            ("local", "Local - Local filesystem"),
                            ("s3", "S3 - Amazon S3"),
                            ("gcs", "GCS - Google Cloud Storage"),
                            ("azure", "Azure - Azure Blob Storage"),
                        ],
                        default="local",
                        help_text="Storage backend used",
                        max_length=30,
                    ),
                ),
                (
                    "bucket",
                    models.CharField(
                        blank=True,
                        help_text="Bucket name (for cloud storage)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Full path to file in storage", max_length=1000
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Generated URL for file access",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type (e.g., image/jpeg)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "size_bytes",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        blank=True,
                        help_text="Image width in pixels (for images)",
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True,
                        help_text="Image height in pixels (for images)",
                        null=True,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="File is publicly accessible",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vehicles", "Vehicles - Vehicle photos/documents"),
                            ("employees", "Employees - Employee photos/documents"),
                            ("bookings", "Bookings - Booking attachments"),
                            ("trips", "Trips - Trip documents"),
                            ("invoices", "Invoices - Invoice files"),
                            ("receipts", "Receipts - Receipt files"),
                            ("avatars", "Avatars - User profile pictures"),
                            ("documents", "Documents - General documents"),
                            ("custom", "Custom - Custom entity types"),
                        ],
                        db_index=True,
                        help_text="Type of entity this file is linked to",
                        max_length=60,
                        null=True,
                    ),
                ),
                (
                    "entity_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID of entity this file is linked to",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this media file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who uploaded this file",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_media_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Media File",
                "verbose_name_plural": "Media Files",
                "db_table": "media_files",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"], name="idx_media_entity"
                    ),
                    models.Index(fields=["uploaded_by"], name="idx_media_uploader"),
                    models.Index(fields=["is_public"], name="idx_media_public"),
                    models.Index(
                        fields=["tenant", "created_at"], name="idx_media_tenant_created"
                    ),
                ],
            },
        ),
    ]
