# Generated by Django 6.0.6 on 2026-07-09 03:50

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("hr", "0001_initial"),
        ("routes", "0001_initial"),
        ("tenants", "0001_initial"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TripTracking",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="High-precision GPS latitude coordinate parsed from the hardware device tracking module",
                        max_digits=10,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="High-precision GPS longitude coordinate parsed from the hardware device tracking module",
                        max_digits=10,
                    ),
                ),
                (
                    "speed_kmh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Real-time velocity metric captured from vehicle OBD/GPS computing matrix units",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "heading",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Compass azimuth rotation angle in degrees indicating current transit direction vectors",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "LOCATION",
                                "Location - Periodic telematics telemetry ping",
                            ),
                            ("STOP", "Stop - Station or roadside stationary pause"),
                            ("START", "Start - Acceleration from stationary state"),
                            (
                                "BREAKDOWN",
                                "Breakdown - Mechanical or operational failure emergency",
                            ),
                            (
                                "ARRIVAL",
                                "Arrival - Geofence breach at final destination station",
                            ),
                        ],
                        help_text="The classification token categorizing the behavioral status of the vehicle at this specific record node",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        help_text="Timezone-aware timestamp logging exactly when this telematics payload was written (Partition Routing Key)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Tracking Telemetry Log",
                "verbose_name_plural": "Trip Tracking Telemetry Logs",
                "db_table": "trip_tracking",
                "ordering": ["-recorded_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TripSchedule",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique business identification string code per tenant (e.g., FIX-HANOI-0600)",
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code must contain only uppercase letters, numbers, hyphens, and underscores",
                                regex="^[A-Z0-9\\-_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "departure_time",
                    models.TimeField(
                        help_text="The official clock time when a vehicle must leave the origin station"
                    ),
                ),
                (
                    "arrival_time",
                    models.TimeField(
                        blank=True,
                        help_text="Estimated or planned clock time when the vehicle reaches the terminal hub",
                        null=True,
                    ),
                ),
                (
                    "days_of_week",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(),
                        default=list,
                        help_text="Array of repeating weekday integer index trackers (1=Monday, 2=Tuesday, ..., 7=Sunday)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Designates whether this timetable sequence is operational and actively generating daily trip records",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="The calendar commencement date when this operational schedule becomes effective",
                        null=True,
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        help_text="The calendar closing date when this operational schedule ceases to be valid",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="The recommended or required vehicle specification profile for this schedule allocation slot",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_schedules",
                        to="vehicles.vehiclecategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        help_text="The core spatial transportation route this schedule runs on",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trip_schedules",
                        to="routes.route",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant owner of this recurring scheduling timetable blueprint",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_schedules",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Schedule",
                "verbose_name_plural": "Trip Schedules",
                "db_table": "trip_schedules",
                "ordering": ["tenant", "route", "departure_time"],
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique commercial business code matching ticketing indexes (e.g., HAN-SGN-20260530-01)",
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code must contain only uppercase letters, numbers, hyphens, and underscores",
                                regex="^[A-Z0-9\\-_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "departure_time",
                    models.DateTimeField(
                        db_index=True,
                        help_text="The official planned/scheduled calendar date and time for departure gate release",
                    ),
                ),
                (
                    "estimated_arrival",
                    models.DateTimeField(
                        blank=True,
                        help_text="The calculated estimated date and time for terminal destination arrival logs",
                        null=True,
                    ),
                ),
                (
                    "actual_departure",
                    models.DateTimeField(
                        blank=True,
                        help_text="The exact physical timestamp logged when wheel rotation began past terminal gates",
                        null=True,
                    ),
                ),
                (
                    "actual_arrival",
                    models.DateTimeField(
                        blank=True,
                        help_text="The exact physical timestamp logged when the asset successfully safely docked at destination terminal",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled - Planned upcoming journey"),
                            ("BOARDING", "Boarding - Welcome gates open at terminal"),
                            ("DEPARTED", "Departed - En-route active on highway"),
                            ("ARRIVED", "Arrived - Docked at terminal destination"),
                            ("CANCELLED", "Cancelled - Aborted operation line"),
                            ("DELAYED", "Delayed - Postponed timing window"),
                            (
                                "DIVERTED",
                                "Diverted - Transiting via alternative bypass",
                            ),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        help_text="The core operational stage representing current journey lifecycle status",
                        max_length=30,
                    ),
                ),
                (
                    "cancel_reason",
                    models.TextField(
                        blank=True,
                        help_text="Explicit legal/operational annotation stating why a scheduled line was aborted",
                        null=True,
                    ),
                ),
                (
                    "delay_reason",
                    models.TextField(
                        blank=True,
                        help_text="Context annotations explaining schedule drift variables (e.g., highway congestion, tire repairs)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Miscellaneous operational dispatcher logging data sheets, special alerts, or crew notes",
                        null=True,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="The dispatch managing branch station hub holding tracking accountability",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips",
                        to="branches.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        help_text="The active physical transportation route corridor assigned to this trip",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="routes.route",
                    ),
                ),
                (
                    "seat_map",
                    models.ForeignKey(
                        blank=True,
                        help_text="The configuration matrix snapshot blueprint determining layout inventory allocation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips",
                        to="vehicles.seatmap",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant owner of this active operational trip journey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        help_text="The physical commercial fleet asset deployed to execute this journey",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips",
                        to="vehicles.vehicle",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to parent timetable blueprint configuration template if auto-generated",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips",
                        to="trips.tripschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip",
                "verbose_name_plural": "Trips",
                "db_table": "trips",
                "ordering": ["departure_time", "code"],
            },
        ),
        migrations.CreateModel(
            name="TripStaff",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DRIVER", "Driver - Fleet steering operator"),
                            ("ASSISTANT", "Assistant - Trip conductor crew"),
                            ("INSPECTOR", "Inspector - Compliance ticket auditor"),
                        ],
                        db_index=True,
                        help_text="The functional deployment role designated to this staff member inside the vehicle",
                        max_length=30,
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Designates whether the employee has acknowledged and accepted this flight/trip dispatch roster order",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="The staff member assigned to the trip crew panel",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trip_assignments",
                        to="hr.employee",
                    ),
                ),
                (
                    "shift_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific daily working shift boundary profile covering this assignment time matrix",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_crew_shifts",
                        to="hr.shifttype",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        help_text="The active commercial trip journey asset target mapping",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew_assignments",
                        to="trips.trip",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Staff Assignment",
                "verbose_name_plural": "Trip Staff Assignments",
                "db_table": "trip_staff",
                "ordering": ["trip", "role", "employee"],
            },
        ),
        migrations.CreateModel(
            name="DispatchOrder",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware timestamp logging exactly when clearance approval was executed",
                        null=True,
                    ),
                ),
                (
                    "checklist",
                    models.JSONField(
                        default=dict,
                        help_text="Complex data matrix validating dynamic safe pre-departure parameters (e.g., fuel, brakes, safety)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Miscellaneous comments from the supervisor, delay flags, or terminal exceptional logs",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "PENDING",
                                "Pending - Awaiting checklist validation and approval sign-off",
                            ),
                            (
                                "ISSUED",
                                "Issued - Dispatch cleared, vehicle ready for terminal departure",
                            ),
                            (
                                "DEPARTED",
                                "Departed - Vehicle passed exit gate, trip active en-route",
                            ),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="The progression state tracking this dispatch order within the gate house terminal ecosystem",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The active dispatcher or station manager authorizing this departure clearance",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_dispatches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "trip",
                    models.OneToOneField(
                        help_text="The unique commercial trip journey assigned under this dispatch directive paper",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_order",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispatch Order",
                "verbose_name_plural": "Dispatch Orders",
                "db_table": "dispatch_orders",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["PENDING", "ISSUED", "DEPARTED"])
                        ),
                        name="chk_dispatch_order_status",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TripPrice",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "seat_type",
                    models.CharField(
                        choices=[
                            ("SEAT", "Standard Sitting Seat"),
                            ("SLEEPER", "Premium Sleeper Berth"),
                            ("VIP_SEAT", "Luxury VIP Limousine Seat"),
                        ],
                        db_index=True,
                        default="SEAT",
                        help_text="The layout material or tier category mapping this fare rate (e.g., SEAT, SLEEPER)",
                        max_length=30,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The official adult standard ticket base pricing scalar value",
                        max_digits=15,
                    ),
                ),
                (
                    "child_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Concessionary ticket price explicitly allocated for child or minor passengers",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The activation date from which this fare tariff becomes effective and open for bookings"
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        help_text="The closure date when this fare tariff structure ceases to be active (Null implies indefinite)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Designates whether this specific pricing line is actively considered by the ticketing engine",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        help_text="The specific spatial transportation route this tariff applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariffs",
                        to="routes.route",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant owner of this commercial pricing tariff schema",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_prices",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Price Tariff",
                "verbose_name_plural": "Trip Price Tariffs",
                "db_table": "trip_prices",
                "ordering": ["tenant", "route", "seat_type", "-valid_from"],
                "indexes": [
                    models.Index(
                        fields=["route", "seat_type", "is_active"],
                        name="idx_price_booking_lookup",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="tripschedule",
            index=models.Index(
                fields=["is_active", "valid_from", "valid_to"],
                name="idx_sch_lifecycle_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="tripschedule",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="unique_tenant_trip_schedule_code"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["route", "status", "departure_time"],
                name="idx_trip_customer_search",
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["vehicle", "status"], name="idx_trip_fleet_active_tracking"
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="unique_tenant_trip_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "SCHEDULED",
                            "BOARDING",
                            "DEPARTED",
                            "ARRIVED",
                            "CANCELLED",
                            "DELAYED",
                            "DIVERTED",
                        ],
                    )
                ),
                name="chk_trip_status",
            ),
        ),
        migrations.AddIndex(
            model_name="tripstaff",
            index=models.Index(
                fields=["employee", "confirmed"], name="idx_staff_pending_rosters"
            ),
        ),
        migrations.AddConstraint(
            model_name="tripstaff",
            constraint=models.UniqueConstraint(
                fields=("trip", "employee"), name="unique_trip_employee_assignment"
            ),
        ),
    ]
