# Generated by Django 6.0.6 on 2026-07-07 12:19

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="System-internal lookup identifier string token (e.g., OTP_VERIFICATION, TRIP_CANCELLED)",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable administrative title label identifying this blueprint copy layout",
                        max_length=255,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            (
                                "SMS",
                                "SMS - Raw plaintext cellular carrier telecommunication short messages",
                            ),
                            (
                                "EMAIL",
                                "Email - Rich text/HTML messaging structures with formal headers",
                            ),
                            (
                                "PUSH",
                                "Push - Device operating system background alert banner pings",
                            ),
                            (
                                "ZALO",
                                "Zalo - Official localized Zalo Notification Service (ZNS) message blocks",
                            ),
                            (
                                "IN_APP",
                                "In-App - Internal customer account dashboard activity notification bell rows",
                            ),
                        ],
                        db_index=True,
                        help_text="The explicit physical transport gateway medium selected to route this communication data packet",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="The target header caption line text. Heavily utilized by EMAIL blocks; usually sits NULL for SMS.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="The core textual messaging content blueprint layout payload supporting dynamic curly bracket variable slots (e.g., {otp_code})"
                    ),
                ),
                (
                    "variables",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        help_text="Array matrix logging explicit system keywords allowed to reside inside this layout body (e.g., [customer_name, passenger_id])",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Master state switch engine. Disabling this instantly silences this notification pathway across workers",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        default=1,
                        help_text="Tenant corporate node owning and controlling this isolated communications blueprint segment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_templates",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "db_table": "notification_templates",
                "ordering": ["code", "channel"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "tenant_id",
                    models.IntegerField(
                        default=1,
                        help_text="Tenant corporate node owning and financing this communications ledger execution instance",
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            (
                                "USER",
                                "User - Generic console accounts or internal admin portal entities",
                            ),
                            (
                                "CUSTOMER",
                                "Customer - Active consumer passengers or freight logistical clients",
                            ),
                            (
                                "EMPLOYEE",
                                "Employee - On-field fleet transport operational staff or station managers",
                            ),
                        ],
                        help_text="The structural category classification governing the target recipient profile mapping layout",
                        max_length=20,
                    ),
                ),
                (
                    "recipient_id",
                    models.IntegerField(
                        blank=True,
                        help_text="The abstract primary key referencing the target user/customer/employee table row based on recipient_type",
                        null=True,
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        blank=True,
                        help_text="Cellular telecommunication string destination required for SMS or ZALO dispatches",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True,
                        help_text="Electronic digital mail destination address required for EMAIL channel delivery workflows",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        help_text="The explicit physical medium selected to route this communication text block (e.g., SMS, EMAIL, PUSH)",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="The specific message title or email subject text banner used during transmission delivery packages",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="The finalized rendered plaintext or rich HTML text body sent down to third-party telecommunication networks"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "PENDING",
                                "Pending - Staged in transmission queue, awaiting background daemon pickup",
                            ),
                            (
                                "SENT",
                                "Sent - External telecom/email gateway successfully authorized delivery",
                            ),
                            (
                                "FAILED",
                                "Failed - Gateway aborted transaction execution, stalled in error state",
                            ),
                            (
                                "CANCELLED",
                                "Cancelled - Voluntarily terminated by administrative task overrides before dispatch",
                            ),
                        ],
                        default="PENDING",
                        help_text="The real-time operational processing milestone tracking this transaction through queue worker handlers",
                        max_length=20,
                    ),
                ),
                (
                    "retry_count",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Current exponential backoff retry tally tracking delivery attempts made by pipeline workers before failure termination",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "error_msg",
                    models.TextField(
                        blank=True,
                        help_text="Stashes external vendor diagnostic telemetry dumps or exception logs during failed transmission attempts",
                        null=True,
                    ),
                ),
                (
                    "ref_type",
                    models.CharField(
                        blank=True,
                        help_text="The application string name token mapping target business modules (e.g., booking, trip, consignment)",
                        max_length=60,
                        null=True,
                    ),
                ),
                (
                    "ref_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="The corresponding primary key value pointing onto the source domain model indicated by ref_type",
                        null=True,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timezone-aware timestamp logging exactly when the third-party communication channel confirmed delivery clearance",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="The base blueprint template layer utilized to construct this message payload copy text",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="notifications.notificationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Omnichannel Notification Log",
                "verbose_name_plural": "Omnichannel Notification Logs",
                "db_table": "notifications",
                "ordering": ["status", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="notificationtemplate",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code", "channel"),
                name="uq_tenant_notification_template_matrix",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationtemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("channel__in", ["SMS", "EMAIL", "PUSH", "ZALO", "IN_APP"])
                ),
                name="chk_notification_template_channel_enum",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["status", "created_at"], name="idx_notifications_status"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["ref_type", "ref_id"], name="idx_notifications_ref"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["PENDING", "SENT", "FAILED", "CANCELLED"])
                ),
                name="chk_notification_status_rules",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recipient_type__in", ["USER", "CUSTOMER", "EMPLOYEE"])
                ),
                name="chk_notification_recipient_type_enum",
            ),
        ),
    ]
